using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;
using UnityEngine.UI;
using System.Collections.Generic;

public class QuestionButton : UdonSharpBehaviour {
  public Text textBox;
  public Toggle masterToggle;
  public AudioSource clickSound;
  [UdonSynced] public int currentText = -1;
  public int previousText = -1;
  [UdonSynced] public bool masterLocked = false;

  string[] questions = new[] {
    // {"Wholesome", new[] {
    "<b>Wholesome:</b>\nNot felt loved by my family (if you felt loved move)",
    "<b>Wholesome:</b>\nNot believed in a form of religion (if you believed in one move)",
    "<b>Wholesome:</b>\nBeen able to do an impression perfectly",
    "<b>Wholesome:</b>\nSkydived or went hang gliding",
    "<b>Wholesome:</b>\nShot someone in the face, crotch or as* with a paintball or bb gun",
    "<b>Wholesome:</b>\nPlayed laser tag",
    "<b>Wholesome:</b>\nPlayed airsoft at a real airsoft event",
    "<b>Wholesome:</b>\nOwned a 4K TV that was bigger than 55 inches",
    "<b>Wholesome:</b>\nBungee jumped",
    "<b>Wholesome:</b>\nCuddled my pet",
    "<b>Wholesome:</b>\nBeen woken up by my pet",
    "<b>Wholesome:</b>\nBeen into extreme sports (XGames, BMX, Dirt biking, skateboarding, surfing, snowboarding)",
    "<b>Wholesome:</b>\nPeed in the shower",
    "<b>Wholesome:</b>\nChanged my hair color",
    "<b>Wholesome:</b>\nCried over an anime",
    "<b>Wholesome:</b>\nLooked at memes for over an hour",
    "<b>Wholesome:</b>\nNot asked for an order change that was clearly wrong at a restaurant",
    "<b>Wholesome:</b>\nTipped someone less than 20 dollars (if you tip less than 20 dollars move)",
    "<b>Wholesome:</b>\nTipped someone 100 dollars or more (tipped 100 or more, move)",
    "<b>Wholesome:</b>\nColored my nails",
    "<b>Wholesome:</b>\nBroken one of my own bones",
    "<b>Wholesome:</b>\nHurt my own genitals entirely on accident",
    "<b>Wholesome:</b>\nNut checked someone",
    "<b>Wholesome:</b>\nFarted in a locked environment with other people around",
    "<b>Wholesome:</b>\nBeen a part of a prank day at school",
    "<b>Wholesome:</b>\nGotten a tattoo or branding",
    "<b>Wholesome:</b>\nHad a mine phase (little kids going \"mine mine mine\" to everything)",
    "<b>Wholesome:</b>\nLived in the same place for more than 5 years",
    "<b>Wholesome:</b>\nExperienced an embarrassing moment",
    "<b>Wholesome:</b>\nTripped someone",
    "<b>Wholesome:</b>\nBeen in a play with a lead role",
    "<b>Wholesome:</b>\nHad more than one pet",
    "<b>Wholesome:</b>\nSmoked or vaped",
    "<b>Wholesome:</b>\nHad the latest phone model",
    "<b>Wholesome:</b>\nOwned a Nintendo 64, SNES, Sega Dreamcast or a PS1",
    "<b>Wholesome:</b>\nTold a lie to save someone from the truth",
    "<b>Wholesome:</b>\nNot cared about my appearance (don't care how you look, move)",
    "<b>Wholesome:</b>\nBeen more into Star Wars or Star Trek",
    "<b>Wholesome:</b>\nCried over a movie scene",
    "<b>Wholesome:</b>\nDeeply invested in a show and or anime",
    "<b>Wholesome:</b>\nWatched a cartoon that is over 50 years old",
    "<b>Wholesome:</b>\nWatched fireworks",
    "<b>Wholesome:</b>\nBeen a part of a parade",
    "<b>Wholesome:</b>\nWon a dare or bet that was for 50 dollars or more",
    "<b>Wholesome:</b>\nHad the Flu",
    "<b>Wholesome:</b>\nHad Food Poisoning",
    "<b>Wholesome:</b>\nEnded up p*ssing myself from laughing",
    "<b>Wholesome:</b>\nSneezed and sh*t myself",
    "<b>Wholesome:</b>\nSneezed while taking a p*ss while standing",
    "<b>Wholesome:</b>\nDone volunteer work",
    "<b>Wholesome:</b>\nAte a Ghost Pepper or South Carolina Reaper",
    "<b>Wholesome:</b>\nBuilt something or repaired something",
    "<b>Wholesome:</b>\nCelebrated a birthday after 21",
    "<b>Wholesome:</b>\nGone to a beach",
    "<b>Wholesome:</b>\nGone camping",
    "<b>Wholesome:</b>\nHeld a subscription service for over a year",
    "<b>Wholesome:</b>\nSang or rapped along with a song",
    "<b>Wholesome:</b>\nBeen influenced by a show or movie in a good way",
    "<b>Wholesome:</b>\nWanted to live in a different time period",
    "<b>Wholesome:</b>\nWorn dirty underwear or clothes",
    "<b>Wholesome:</b>\nEnjoyed a comic of any kind",
    "<b>Wholesome:</b>\nBeen to a drag race",
    "<b>Wholesome:</b>\nBeen a part of Secret Santa",
    "<b>Wholesome:</b>\nBeen to a Monster Truck Rally",
    "<b>Wholesome:</b>\nPlayed a card game",
    "<b>Wholesome:</b>\nPlayed Uno with over 25 cards in my hand",
    "<b>Wholesome:</b>\nSlept in a bathtub",
    "<b>Wholesome:</b>\nHad an imaginary friend",
    "<b>Wholesome:</b>\nBeen to a garage or yard sale",
    "<b>Wholesome:</b>\nPeeked on my own presents; birthday, Christmas or otherwise.",
    "<b>Wholesome:</b>\nBeen an impulsive buyer",
    "<b>Wholesome:</b>\nBinge watched an entire show or anime",
    "<b>Wholesome:</b>\nBroken a phone",
    "<b>Wholesome:</b>\nBeen on a boat or cruise",
    "<b>Wholesome:</b>\nBeen to theme park (Six flags, Universal Studios, Disney Land, etc.)",
    "<b>Wholesome:</b>\nHad braces while over the age of 18",
    "<b>Wholesome:</b>\nDonated blood or an organ",
    "<b>Wholesome:</b>\nHad an organ or a piece of an organ removed",
    "<b>Wholesome:</b>\nPlayed \"I'll show you mine if you show me your's\"",
    "<b>Wholesome:</b>\nCared about my zodiac sign",
    "<b>Wholesome:</b>\nGiven a speech",
    "<b>Wholesome:</b>\nRescued an animal",
    "<b>Wholesome:</b>\nHelped someone without ever expecting something in return",
    "<b>Wholesome:</b>\nTaken a friend out when they couldn't afford it and covered them without expecting anything in return",
    "<b>Wholesome:</b>\nBeen the friend to move the couch and help bury the body",
    "<b>Wholesome:</b>\nFought with a friend over something stupid",
    "<b>Wholesome:</b>\nBeen friendzoned and happy about it",
    "<b>Wholesome:</b>\nBeen the friend who let another crash at their home",
    "<b>Wholesome:</b>\nBeen the friend that helped someone get into better shape",
    "<b>Wholesome:</b>\nHelped someone who was homeless and not with money or food",
    "<b>Wholesome:</b>\nGiven a friend something that was worth over 500 dollars as a gift",
    "<b>Wholesome:</b>\nBeen happy for a friend doing better or succeeding at something",
    "<b>Wholesome:</b>\nStood up for someone I did or did not know",
    "<b>Wholesome:</b>\nLoved the smell of fresh gasoline",
    "<b>Wholesome:</b>\nLoved the smell of dry erase markers and or sharpies",
    "<b>Wholesome:</b>\nHad an allergic reaction to something that nearly killed me",
    "<b>Wholesome:</b>\nBeen spent an entire day on Youtube",
    "<b>Wholesome:</b>\nPlayed a game in black and white or CRT",
    "<b>Wholesome:</b>\nHad hair that touched my butt",
    "<b>Wholesome:</b>\nDrawn on someone's face while they were asleep",
    "<b>Wholesome:</b>\nLaughed while drinking and had the drink come out my nose",
    "<b>Wholesome:</b>\nLaughed at something I should not",
    "<b>Wholesome:</b>\nBeen part of a church activity (Christmas caroling, Easter hunts, volunteer work, etc.)",
    "<b>Wholesome:</b>\nUsed a pickup line and bombed it",
    "<b>Wholesome:</b>\nWished life was like an anime or a game",
    "<b>Wholesome:</b>\nBadly f*cked up a text due to auto correct",
    "<b>Wholesome:</b>\nFixed up a junk yard car and used it as my main vehicle",
    "<b>Wholesome:</b>\nFully committed to a cross dress outfit",
    "<b>Wholesome:</b>\nUnderstood something my parents did or said years later",
    "<b>Wholesome:</b>\nSat on a red ant hill",
    "<b>Wholesome:</b>\nF*cked with a bee, wasp and or hornet nest",
    "<b>Wholesome:</b>\nBullied the bully",
    "<b>Wholesome:</b>\nMistaken a fart and sh*t myself",
    "<b>Wholesome:</b>\nPracticed any form of Martial Arts",
    "<b>Wholesome:</b>\nLost or had my swim wear stolen while wearing it",
    "<b>Wholesome:</b>\nActually kept my New Year's Resolution goal",
    "<b>Wholesome:</b>\nBeen a volunteer firefighter or first responder",
    "<b>Wholesome:</b>\nThrown actual sh*t at someone",
    "<b>Wholesome:</b>\nWalked out of a room naked or in my underwear into a crowded room unknowingly",
    "<b>Wholesome:</b>\nGone mudding",
    "<b>Wholesome:</b>\nGone redneck surfing (area flooded - attach rope to a truck, proceed into flooded area at high speeds while on a surfboard)",
    "<b>Wholesome:</b>\nBeen brake checked or brake checked someone",
    "<b>Wholesome:</b>\nDropped my phone in a filled toilet",
    "<b>Wholesome:</b>\nFailed to open a door more than once in the same door way (one door is locked, the other is pull not push)",
    "<b>Wholesome:</b>\nHad a friend who I considered more family than my actual family",
    "<b>Wholesome:</b>\nBeen able to roll my tongue in any way",
    "<b>Wholesome:</b>\nSeen the Northern Lights",
    // }},
    // {"School", new[] {
    "<b>School:</b>\nNot been the one to command a project (always the leader, move)",
    "<b>School:</b>\nCheated on a test and passed",
    "<b>School:</b>\nCopied a classmate's work and passed",
    "<b>School:</b>\nServed detention",
    "<b>School:</b>\nGot suspended",
    "<b>School:</b>\nGot kicked out of a school",
    "<b>School:</b>\nGot expelled from a school",
    "<b>School:</b>\nFailed a grade or course",
    "<b>School:</b>\nBeen held back a grade",
    "<b>School:</b>\nSkipped a grade",
    "<b>School:</b>\nGot into a fight at school",
    "<b>School:</b>\nHad a school shooting",
    "<b>School:</b>\nBrought a weapon to school",
    "<b>School:</b>\nBrought drugs, booze, tobacco or nicotine products to school",
    "<b>School:</b>\nBeen caught with drugs, booze, tobacco, or nicotine products at school",
    "<b>School:</b>\nUsed an unconventional item as a weapon (book, desk, etc.)",
    "<b>School:</b>\nHad problems with attendance",
    "<b>School:</b>\nTaken senior prank day or seen a prank day go way over the line",
    "<b>School:</b>\nDrugged a classroom (pot brownies and no one knew, etc.)",
    "<b>School:</b>\nWon multiple sports games in a row",
    "<b>School:</b>\nGone to nationals in a sports team",
    "<b>School:</b>\nGone to nationals and won in a sports team",
    "<b>School:</b>\nPlayed in Band or Orchestra",
    "<b>School:</b>\nTraveled out of state to an event with Band or Orchestra",
    "<b>School:</b>\nBeen a class representative",
    "<b>School:</b>\nBeen part of yearbook",
    "<b>School:</b>\nGraduated primary, intermediate, and high school",
    "<b>School:</b>\nGone to boarding school",
    "<b>School:</b>\nGone to a year round school",
    "<b>School:</b>\nGone to private school",
    "<b>School:</b>\nBeen horribly humiliated at school and actually changed schools",
    "<b>School:</b>\nBeen home schooled",
    "<b>School:</b>\nLearned one or more languages at school",
    "<b>School:</b>\nTaken an art class",
    "<b>School:</b>\nTaken a class in Automotive",
    "<b>School:</b>\nTaken a Shop class",
    "<b>School:</b>\nTaken a Wood Working class",
    "<b>School:</b>\nTaken a Home Ec class",
    "<b>School:</b>\nTaken a Veterinarian class",
    "<b>School:</b>\nTaken a Criminal Justice class",
    "<b>School:</b>\nTaken a JROTC or equivalent class (boot camp for kids)",
    "<b>School:</b>\nTaken a Law class",
    "<b>School:</b>\nTaken a Business class",
    "<b>School:</b>\nTaken a First Responder, CPR, or EMT-Basic training class",
    "<b>School:</b>\nBeen in AP classes",
    "<b>School:</b>\nBeen on the honor roll or dean's list",
    "<b>School:</b>\nBeen in a food fight",
    "<b>School:</b>\nSkipped class or classes",
    "<b>School:</b>\nPlayed hooky",
    "<b>School:</b>\nNot gone to a dance",
    "<b>School:</b>\nAttended Prom",
    "<b>School:</b>\nHad a snow day and school was cancelled",
    "<b>School:</b>\nBeen in Summer School",
    "<b>School:</b>\nUsed what I learned in school",
    "<b>School:</b>\nGot a grant or scholarship",
    "<b>School:</b>\nKnew what I was going to become after High School",
    "<b>School:</b>\nHad a job while attending school",
    "<b>School:</b>\nSold drugs or booze at school",
    "<b>School:</b>\nBeen the person who bought people smokes (were you 18 and bought people cigs who weren't 18? Move.)",
    "<b>School:</b>\nWalked more than a mile to school",
    "<b>School:</b>\nTaken remedial classes",
    "<b>School:</b>\nBeen in special education classes",
    "<b>School:</b>\nBeen in the GIFTed program (\"Genius\" program)",
    "<b>School:</b>\nThought I would be the first in my family to finish High School and get my Diploma (first to get a diploma, congratz move!)",
    "<b>School:</b>\nGot a Diploma or GED",
    "<b>School:</b>\nNot forgotten the Fitness Gram Pacer test (still remember this? move)",
    "<b>School:</b>\nLaughed at the window lickers for doing something",
    "<b>School:</b>\nBeen pantsed in front of people at school",
    "<b>School:</b>\nRead a book for English class and actually enjoyed it",
    "<b>School:</b>\nBeen on a field trip to a park",
    "<b>School:</b>\nBeen on a field trip to a play",
    "<b>School:</b>\nBeen on the field trip to Washington D.C. or a different capitol",
    "<b>School:</b>\nFinished someone off in Dodgeball",
    "<b>School:</b>\nKnocked someone out at school",
    "<b>School:</b>\nPut the school under lockdown by doing something really stupid",
    "<b>School:</b>\nForged my parent's signature",
    "<b>School:</b>\nFallen asleep at school",
    "<b>School:</b>\nHad a class pet",
    "<b>School:</b>\nHad a tutor or been a tutor",
    "<b>School:</b>\nHad my phone taken at school",
    "<b>School:</b>\nBeen a teacher's pet or teacher's aid",
    "<b>School:</b>\nPulled the fire alarm on purpose",
    "<b>School:</b>\nDriven my own vehicle to school",
    "<b>School:</b>\nDropped out of school",
    "<b>School:</b>\nTold a teacher off (told a teacher to f*ck off, called them out on something, etc.)",
    "<b>School:</b>\nAte glue",
    "<b>School:</b>\nBeen a part of a club",
    "<b>School:</b>\nBeen in sports for four years or more",
    "<b>School:</b>\nBeen taken out of a class by the police",
    "<b>School:</b>\nBeen a part of a hazing ritual (Seniors pick on Freshmen)",
    "<b>School:</b>\nStood up to a bully and got them to back off or put them down",
    "<b>School:</b>\nHad a relationship that lasted from the start of the school year and last till the end of it or longer",
    // }},
    // {"Work", new[] {
    "<b>Work:</b>\nStolen money from a register while working at it",
    "<b>Work:</b>\nTried to blackmail someone at work",
    "<b>Work:</b>\nCaught coworkers f*cking or been caught",
    "<b>Work:</b>\nF*cked my boss for a position or raise",
    "<b>Work:</b>\nLied out right to a customer or client's face",
    "<b>Work:</b>\nTold the honest and brutal truth to a customer or client's face",
    "<b>Work:</b>\nBeen robbed at a place I was working at",
    "<b>Work:</b>\nWorked in a place where there was an active shooter",
    "<b>Work:</b>\nStolen from where I've worked",
    "<b>Work:</b>\nGotten into a fight while at work that became physical",
    "<b>Work:</b>\nBeen fired",
    "<b>Work:</b>\nWorked retail, restaurants, bars, clubs, sales, or customer service",
    "<b>Work:</b>\nHad a job that paid over 50,000 yearly",
    "<b>Work:</b>\nHad a job that paid over 100,000 yearly",
    "<b>Work:</b>\nHad to fire someone",
    "<b>Work:</b>\nHad a policy put in place that was so stupid or counter productive I quit",
    "<b>Work:</b>\nHad a sh*tty boss",
    "<b>Work:</b>\nRatted out a coworker for being lazy",
    "<b>Work:</b>\nBeen threatened by a customer or client",
    "<b>Work:</b>\nRealized I need to work out because of my job",
    "<b>Work:</b>\nWorked Night or Graveyard (19:00 - 08:00)",
    "<b>Work:</b>\nWork more than 12 hours in a day",
    "<b>Work:</b>\nWork more than 100 hours in a week",
    "<b>Work:</b>\nExperienced extremely dangerous conditions where I work",
    "<b>Work:</b>\nThought I could get my dream job",
    "<b>Work:</b>\nTraveled for work",
    "<b>Work:</b>\nJust wanted to watch the place I work at be burned to the ground",
    "<b>Work:</b>\nWorked a day in my life",
    "<b>Work:</b>\nBeen laid off or asked to resign",
    "<b>Work:</b>\nWorked more than one job at a time",
    "<b>Work:</b>\nGotten someone fired",
    "<b>Work:</b>\nYelled at a customer or client",
    "<b>Work:</b>\nGotten a promotion within a period of six months",
    "<b>Work:</b>\nBeen given Employee of the Month or an award for my work",
    "<b>Work:</b>\nBroke something at work on purpose",
    "<b>Work:</b>\nFallen asleep while at work",
    "<b>Work:</b>\nBeen seriously injured at work",
    "<b>Work:</b>\nLeft without a two week notice",
    "<b>Work:</b>\nLeft with a two week notice but quit earlier",
    "<b>Work:</b>\nWorked with Customer Support",
    "<b>Work:</b>\nHad to explain how something actually works",
    "<b>Work:</b>\nTo deal with a customer who was incredibly stupid or lacked the most basic of understandings of something",
    "<b>Work:</b>\nGone to work drunk or high or while at work got drunk or high",
    "<b>Work:</b>\nBeen sued for something I said or did at work",
    "<b>Work:</b>\nHeld a job for longer than 1 year",
    "<b>Work:</b>\nHeld a job for less than a month",
    "<b>Work:</b>\nHeld a job that was commission based only",
    "<b>Work:</b>\nGot a bonus",
    "<b>Work:</b>\nGot a raise of 5 dollars an hour or more within a year",
    "<b>Work:</b>\nMade a sale for over 10,000 dollars",
    "<b>Work:</b>\nMade a sale for over 1 million dollars",
    "<b>Work:</b>\nLearned something so bad about a place I worked at I would never eat or shop there again",
    "<b>Work:</b>\nBeen in a Union or Guild",
    "<b>Work:</b>\nBeen a Supervisor or Manager",
    "<b>Work:</b>\nBeen on the phone with a customer or client for longer than an hour",
    "<b>Work:</b>\nBeen part of a large event such as a convention, wedding, or otherwise",
    "<b>Work:</b>\nHad someone bad mouth me in a different language and then spoke to them in that language",
    "<b>Work:</b>\nBeen a freelancer or contractor",
    "<b>Work:</b>\nMade over 250 dollars with a single art piece I made",
    "<b>Work:</b>\nHad to file a police report over an incident that happened at work",
    "<b>Work:</b>\nHad a job I actually was happy about",
    "<b>Work:</b>\nHad a job while I was homeless",
    "<b>Work:</b>\nBeen discriminated against where I work",
    "<b>Work:</b>\nBeen demoted",
    "<b>Work:</b>\nCalled someone out who had been partying the night before and told them to get to work",
    "<b>Work:</b>\nHad to ask or clean up someone's period",
    // }},
    // {"Fetish", new[] {
    "<b>Fetish:</b>\nLiked futas, shemales, or trans",
    "<b>Fetish:</b>\nLiked furries",
    "<b>Fetish:</b>\nLiked hentai",
    "<b>Fetish:</b>\nLiked Sissy training",
    "<b>Fetish:</b>\nLiked gore and or vore",
    "<b>Fetish:</b>\nLiked amputation",
    "<b>Fetish:</b>\nLiked impregnancy, pregnancy, and or breeding",
    "<b>Fetish:</b>\nLiked Lactation",
    "<b>Fetish:</b>\nLiked inflation",
    "<b>Fetish:</b>\nLiked tentacles",
    "<b>Fetish:</b>\nLiked monsters, demons, orcs, etc.",
    "<b>Fetish:</b>\nLiked fantasy beings such as elves, angels, mages, etc.",
    "<b>Fetish:</b>\nLiked BDSM",
    "<b>Fetish:</b>\nLiked rough sex",
    "<b>Fetish:</b>\nLiked incest",
    "<b>Fetish:</b>\nLiked lollis",
    "<b>Fetish:</b>\nLiked Yaoi or Yuri",
    // "<b>Fetish:</b>\nLiked r*pe",
    "<b>Fetish:</b>\nLiked hypnosis, indoctrination, or brainwashing",
    "<b>Fetish:</b>\nLiked Slavery",
    "<b>Fetish:</b>\nLiked masochism",
    "<b>Fetish:</b>\nLiked sadism",
    "<b>Fetish:</b>\nLiked roleplay of any nature",
    "<b>Fetish:</b>\nLiked double penetration more",
    "<b>Fetish:</b>\nLiked voyeurism",
    "<b>Fetish:</b>\nLiked exhibitionism",
    "<b>Fetish:</b>\nLiked anal and or pegging",
    "<b>Fetish:</b>\nLiked over sized c*cks",
    "<b>Fetish:</b>\nLiked feet",
    "<b>Fetish:</b>\nLiked kissing or making out",
    "<b>Fetish:</b>\nLiked sloppy seconds",
    "<b>Fetish:</b>\nLiked c*m female or male",
    "<b>Fetish:</b>\nLiked threesomes and or foursomes",
    "<b>Fetish:</b>\nLiked vampyrism",
    "<b>Fetish:</b>\nLiked water sports",
    "<b>Fetish:</b>\nLiked holding hands",
    "<b>Fetish:</b>\nLiked glory holes",
    "<b>Fetish:</b>\nLiked Shouta",
    "<b>Fetish:</b>\nLiked deflowering",
    "<b>Fetish:</b>\nLiked period sex",
    "<b>Fetish:</b>\nLiked teasing",
    "<b>Fetish:</b>\nLiked nude exercise",
    "<b>Fetish:</b>\nLiked lingerie",
    "<b>Fetish:</b>\nLiked quickies",
    "<b>Fetish:</b>\nLiked long lasting sex specifically 3 hours or longer",
    "<b>Fetish:</b>\nLiked bathroom, bathtub and or shower sex",
    "<b>Fetish:</b>\nLiked watching or being watched while masturbating",
    "<b>Fetish:</b>\nLiked professional sex such as an actual teacher and student",
    "<b>Fetish:</b>\nLiked older women or men of 10 years or more",
    // "<b>Fetish:</b>\nLiked younger women or men of 10 years or more",
    "<b>Fetish:</b>\nLiked breasts more than a*s",
    "<b>Fetish:</b>\nLiked p*ssy more than c*ck",
    "<b>Fetish:</b>\nLiked c*ck more than p*ssy",
    "<b>Fetish:</b>\nLiked midgets (4 foot 11 inches) or shorter people",
    "<b>Fetish:</b>\nLiked skinny people",
    "<b>Fetish:</b>\nLiked taller people",
    "<b>Fetish:</b>\nLiked fat people",
    "<b>Fetish:</b>\nLiked petite people",
    "<b>Fetish:</b>\nLiked muscular people",
    "<b>Fetish:</b>\nLiked half breeds more such as nekos and wolf boys",
    "<b>Fetish:</b>\nLiked giving oral more",
    "<b>Fetish:</b>\nLiked bimbos or kens",
    "<b>Fetish:</b>\nLiked body hair",
    "<b>Fetish:</b>\nLiked corruption",
    "<b>Fetish:</b>\nLiked intoxicated sex",
    "<b>Fetish:</b>\nLiked nerds or geeks",
    "<b>Fetish:</b>\nLiked beastiality or zoology",
    "<b>Fetish:</b>\nLiked smoking",
    "<b>Fetish:</b>\nLiked c*m swapping (kissing someone with c*m in their mouth)",
    "<b>Fetish:</b>\nLiked being c*mmed on or c*mming on more (facial)",
    "<b>Fetish:</b>\nLiked being c*mmed in or c*mming in more (creampie)",
    "<b>Fetish:</b>\nLiked cannibalism",
    "<b>Fetish:</b>\nLiked ritual sex",
    "<b>Fetish:</b>\nGotten horny over an accent",
    "<b>Fetish:</b>\nGotten horny over how someone spoke",
    "<b>Fetish:</b>\nLiked ASMR",
    "<b>Fetish:</b>\nLiked masturbation instruction",
    "<b>Fetish:</b>\nLiked video game porn",
    "<b>Fetish:</b>\nLiked ShadBase",
    "<b>Fetish:</b>\nLiked Maids and or Butlers",
    "<b>Fetish:</b>\nLiked Nurses and or Doctors",
    "<b>Fetish:</b>\nLiked vanilla sex",
    "<b>Fetish:</b>\nLiked romantic sex",
    "<b>Fetish:</b>\nLiked erp or cyber sex more than real sex",
    "<b>Fetish:</b>\nLiked Necrophilia",
    "<b>Fetish:</b>\nLiked age play",
    "<b>Fetish:</b>\nLiked C*cking or cuckolding",
    "<b>Fetish:</b>\nLiked Domination",
    "<b>Fetish:</b>\nLiked Submissives",
    "<b>Fetish:</b>\nLiked kidnapping",
    "<b>Fetish:</b>\nLiked Shibari",
    "<b>Fetish:</b>\nLiked suspension",
    "<b>Fetish:</b>\nLiked worship play",
    "<b>Fetish:</b>\nLiked dungeons",
    "<b>Fetish:</b>\nLiked electrocution",
    "<b>Fetish:</b>\nLiked Blackmail",
    "<b>Fetish:</b>\nLiked public humiliation",
    "<b>Fetish:</b>\nLiked remote controlled toys",
    "<b>Fetish:</b>\nLiked toys",
    "<b>Fetish:</b>\nLiked tattooing, carving and or branding",
    "<b>Fetish:</b>\nLiked piercings",
    "<b>Fetish:</b>\nLiked wax play",
    "<b>Fetish:</b>\nLiked rope and or chains",
    "<b>Fetish:</b>\nLiked knife play",
    "<b>Fetish:</b>\nLiked collars",
    "<b>Fetish:</b>\nLiked blindfolds and or gags",
    "<b>Fetish:</b>\nLiked dirty talk or humiliation",
    "<b>Fetish:</b>\nLiked breathplay in any form (choking or being choked)",
    "<b>Fetish:</b>\nLiked injections of any nature",
    "<b>Fetish:</b>\nLiked fire play (burning or being burned)",
    "<b>Fetish:</b>\nLiked edging",
    "<b>Fetish:</b>\nLiked insertion play or fisting",
    "<b>Fetish:</b>\nLiked Pet Play",
    "<b>Fetish:</b>\nLiked Latex and or leather",
    "<b>Fetish:</b>\nLiked spanking, paddling, whipping, and or flogging",
    "<b>Fetish:</b>\nLiked Gorean",
    "<b>Fetish:</b>\nLiked Bears (Big hairy, muscle or fat guy - gay. Very gay.)",
    "<b>Fetish:</b>\nLiked Twinks (Stereotype princess gay guy.)",
    "<b>Fetish:</b>\nLiked MILFs (Mother I'd Like to F*ck)",
    "<b>Fetish:</b>\nLiked Cougars (Age 35+ going for younger men/women)",
    "<b>Fetish:</b>\nLiked Butch women (tom boy girl - acts like a boy)",
    "<b>Fetish:</b>\nLiked Femme women (girly girl)",
    "<b>Fetish:</b>\nLiked wearing heels during sex",
    "<b>Fetish:</b>\nLiked anal more than another hole",
    "<b>Fetish:</b>\nLiked clothed sex",
    "<b>Fetish:</b>\nLiked ice play",
    "<b>Fetish:</b>\nLiked food play",
    "<b>Fetish:</b>\nLiked Slime and or Bukk*ke",
    // }},
    // {"Couples", new[] {
    "<b>Couples:</b>\nStuck it in the wrong hole",
    "<b>Couples:</b>\nHad make up sex the same day of the fight",
    "<b>Couples:</b>\nHad make up sex in an hour of the fight",
    "<b>Couples:</b>\nHad drunk or high sex",
    "<b>Couples:</b>\nOffered sex to get something done",
    "<b>Couples:</b>\nBeen in an open relationship",
    "<b>Couples:</b>\nBeen the side piece",
    "<b>Couples:</b>\nAsked for a threesome",
    "<b>Couples:</b>\nBeen into swinging",
    "<b>Couples:</b>\nExperimented with anal or pegging",
    "<b>Couples:</b>\nBeen with someone 10 years older or younger",
    "<b>Couples:</b>\nRoleplayed with my significant other erotic or otherwise",
    "<b>Couples:</b>\nHad birthday or holiday sex",
    "<b>Couples:</b>\nBeen in engaged or married",
    "<b>Couples:</b>\nSpoken up at wedding and got it cancelled",
    "<b>Couples:</b>\nStood someone up because I was too high or drunk",
    "<b>Couples:</b>\nHad a one night stand that turned into a relationship the following day",
    "<b>Couples:</b>\nMet someone in a game of any variety and then in real life",
    "<b>Couples:</b>\nDated someone who was a psychopath or sociopath",
    "<b>Couples:</b>\nBroke up with someone over the phone",
    "<b>Couples:</b>\nCheated",
    "<b>Couples:</b>\nBeen with someone because of their money",
    "<b>Couples:</b>\nStayed with someone just because of the sex",
    "<b>Couples:</b>\nHad a threesome with my significant other and a relative of theirs or mine (eample: you f*cked her and her sister)",
    "<b>Couples:</b>\nCheated while my significant other was deployed",
    "<b>Couples:</b>\nCalled someone the wrong name during sex",
    "<b>Couples:</b>\nStole from my significant other",
    "<b>Couples:</b>\nBeen on blind date that worked out",
    "<b>Couples:</b>\nHad a friend with benefits",
    "<b>Couples:</b>\nHad to give up on someone I love because they were no longer stable",
    "<b>Couples:</b>\nFell out of love with someone",
    "<b>Couples:</b>\nBet against my significant other",
    "<b>Couples:</b>\nLied about my interests in someone just to date someone",
    "<b>Couples:</b>\nTricked my significant other with a pregnancy scare",
    "<b>Couples:</b>\nBeen in an open relationship",
    "<b>Couples:</b>\nBelieved in love at first sight",
    "<b>Couples:</b>\nBelieved I could tell my significant other literally everything without fear",
    "<b>Couples:</b>\nStood someone up",
    "<b>Couples:</b>\nHumiliated an Ex",
    "<b>Couples:</b>\nF*cked something up for my significant other",
    "<b>Couples:</b>\nHad to lie about how much a hobby costs",
    "<b>Couples:</b>\nWatched porn with a significant other",
    "<b>Couples:</b>\nCheated on someone through a video game",
    "<b>Couples:</b>\nEnded up with someone from a roleplay family I was part of (Example: RPing as a father and you end up dating your RP mother IRL)",
    "<b>Couples:</b>\nBeen with more than one person at the same time",
    "<b>Couples:</b>\nBroken up with someone because of something they do or began doing",
    "<b>Couples:</b>\nFell in love at first sight with someone and ended up dating them",
    "<b>Couples:</b>\nTold someone I loved them within the first month of dating them",
    "<b>Couples:</b>\nBeen with someone for more than a year",
    "<b>Couples:</b>\nBeen with someone less than a week",
    "<b>Couples:</b>\nBeen in a stable relationship",
    "<b>Couples:</b>\nGone back to a bad Ex",
    "<b>Couples:</b>\nSettled for someone",
    "<b>Couples:</b>\nKicked someone out of my life which resulted in them being homeless",
    "<b>Couples:</b>\nMet someone in a club or bar",
    "<b>Couples:</b>\nMet someone where I worked",
    "<b>Couples:</b>\nTold someone I would die for them and meant it",
    "<b>Couples:</b>\nBeen told I was a great listener",
    "<b>Couples:</b>\nHad a fight with my current significant other",
    "<b>Couples:</b>\nFelt used in relationship",
    "<b>Couples:</b>\nDated someone who is trans",
    "<b>Couples:</b>\nHad a kiss that was pure electricity",
    "<b>Couples:</b>\nBeen happier than wearing something my significant other owned (Example: girlfriend in boyfriend's shirt)",
    "<b>Couples:</b>\nSpent more than 200 dollars on lingerie in a single purchase",
    "<b>Couples:</b>\nUsed toys with my significant other",
    "<b>Couples:</b>\nWatched freaky or kinky porn with my significant other",
    "<b>Couples:</b>\nWorked in the sex or adult industry in any way while with someone",
    "<b>Couples:</b>\nSpent more than 200 dollars on sex toys in a single purchase",
    "<b>Couples:</b>\nTried to make a relationship work",
    "<b>Couples:</b>\nBeen genuinely happy for another's relationship",
    "<b>Couples:</b>\nMade out for an hour or longer",
    "<b>Couples:</b>\nPlayed with someone's heart",
    "<b>Couples:</b>\nSimply not cared for a feature or trait in my significant other (you hate they're a gamer, etc.)",
    "<b>Couples:</b>\nBelieved you could have a relationship without trust",
    "<b>Couples:</b>\nFelt forced to stay with someone due to their instability (they're suicidal and always talking about it you stay because you're scared they'll do it)",
    "<b>Couples:</b>\nPlanned a romantic date that didn't involve sex",
    "<b>Couples:</b>\nBeen in a situation with my significant other that I did not agree with at all (they start a fight with someone and you are not wanting a part of this)",
    "<b>Couples:</b>\nEaten something spicy only for my significant other to ask for a bite and watch them suffer",
    "<b>Couples:</b>\nDone something special for my significant other that made them cry",
    "<b>Couples:</b>\nHad my heart broken or broke someone's heart",
    "<b>Couples:</b>\nWorried about my significant other actually killing me",
    "<b>Couples:</b>\nF*cked a psycho and did not regret it",
    "<b>Couples:</b>\nBeen in a relationship that lasted for more than 2 years",
    "<b>Couples:</b>\nGot out of the friend zone and dated the person who friend zoned me or I friend zoned",
    "<b>Couples:</b>\nWore something uncomfortable for my significant other",
    "<b>Couples:</b>\nLoved the way my significant other dresses",
    "<b>Couples:</b>\nDressed my significant other",
    "<b>Couples:</b>\nPlayed off something my significant other said that actually hurt",
    "<b>Couples:</b>\nStood up for my significant other",
    "<b>Couples:</b>\nFelt sexier with significant other in my presence",
    "<b>Couples:</b>\nProposed without a ring",
    "<b>Couples:</b>\nFormed a blood pact or oath with a lover",
    // }},
    // {"Illegal", new[] {
    "<b>Illegal:</b>\nBeen jail baited",
    "<b>Illegal:</b>\nRobbed someone",
    "<b>Illegal:</b>\nStolen more than 1,000 dollars worth of items or an item",
    "<b>Illegal:</b>\nScammed someone for more than 1,000 dollars",
    "<b>Illegal:</b>\nShot or stabbed someone",
    "<b>Illegal:</b>\nBought or sold drugs at a weight of 1 pound or more",
    "<b>Illegal:</b>\nBeen a part of or associated with a gang",
    "<b>Illegal:</b>\nTaken or given a bribe",
    "<b>Illegal:</b>\nTaken kidnapped someone or held someone hostage",
    "<b>Illegal:</b>\nSpiked someone (roofies, given pot brownies without the other knowing, etc.)",
    "<b>Illegal:</b>\nPirated any form of media or art",
    "<b>Illegal:</b>\nDone anything on the dark web",
    "<b>Illegal:</b>\nTagged, or stamped something (gang graffiti)",
    "<b>Illegal:</b>\nDone graffiti",
    "<b>Illegal:</b>\nStolen credit card information",
    "<b>Illegal:</b>\nStolen someone's identity",
    "<b>Illegal:</b>\nImpersonated someone",
    "<b>Illegal:</b>\nTrespassed",
    "<b>Illegal:</b>\nStalked someone",
    "<b>Illegal:</b>\nCased a building or residency",
    "<b>Illegal:</b>\nStolen a vehicle",
    "<b>Illegal:</b>\nOwned an illegal weapon",
    "<b>Illegal:</b>\nWanted to and planned a mass murder",
    "<b>Illegal:</b>\nDisposed of a body",
    "<b>Illegal:</b>\nCommitted fraud",
    "<b>Illegal:</b>\nOrganized a robbery with one or more people",
    "<b>Illegal:</b>\nFalsely accused someone of something, went to court and won",
    "<b>Illegal:</b>\nGone awol or deserted",
    "<b>Illegal:</b>\nHired or been a prostitute or escort",
    "<b>Illegal:</b>\nMade or used a malicious program",
    "<b>Illegal:</b>\nStolen cable service",
    "<b>Illegal:</b>\nCommitted vandalism that could result in over 10,000 dollars in damages",
    "<b>Illegal:</b>\nBeen on parole or probation (not school)",
    "<b>Illegal:</b>\nCommitted arson",
    "<b>Illegal:</b>\nHospitalized someone",
    "<b>Illegal:</b>\nBeen part of a riot",
    "<b>Illegal:</b>\nAssaulted a government employee",
    "<b>Illegal:</b>\nTortured someone",
    "<b>Illegal:</b>\nBeen a part of sex trafficking",
    "<b>Illegal:</b>\nBeen publicly intoxicated",
    "<b>Illegal:</b>\nDriven while intoxicated",
    "<b>Illegal:</b>\nCommitted a hate crime",
    "<b>Illegal:</b>\nBeen or wanted to join the KKK, the NAZIs or a different hate group",
    "<b>Illegal:</b>\nBeen part of a malicious campaign on 4ch*n or 8ch*n",
    "<b>Illegal:</b>\nOwned and used illegal fireworks",
    "<b>Illegal:</b>\nWorked in a chop shop",
    "<b>Illegal:</b>\nRepaired something only to have purposely damaged something to further my repair business",
    "<b>Illegal:</b>\nBeen a part of any form of malpractice",
    "<b>Illegal:</b>\nHazed or harassed someone",
    "<b>Illegal:</b>\nStolen from kids on Hall-O-Ween for their candy",
    "<b>Illegal:</b>\nDestroyed someone's house at a party",
    "<b>Illegal:</b>\nSpied on someone with a drone",
    "<b>Illegal:</b>\nBeen a peeping tom",
    "<b>Illegal:</b>\nAbused an animal",
    "<b>Illegal:</b>\nParticipated in dog and c*ck fighting",
    // }},
    // {"Personal", new[] {
    "<b>Personal:</b>\nBeen evicted",
    "<b>Personal:</b>\nGone to college or university and finished what I went for (certificate, license, degree, course, etc.)",
    "<b>Personal:</b>\nHit a parked vehicle",
    "<b>Personal:</b>\nBeen robbed",
    "<b>Personal:</b>\nBeen drugged",
    "<b>Personal:</b>\nThought my political views would change",
    "<b>Personal:</b>\nBelieved in a religion",
    "<b>Personal:</b>\nTried a dark religion like paganism, wicca, satanism, etc.",
    "<b>Personal:</b>\nBeen in a car crash that had a fatality",
    "<b>Personal:</b>\nTried to be trendy",
    "<b>Personal:</b>\nLeft my home country",
    "<b>Personal:</b>\nBeen stabbed or stabbed someone",
    "<b>Personal:</b>\nBeen jumped or jumped someone",
    "<b>Personal:</b>\nShot someone or been shot",
    "<b>Personal:</b>\nBeen awake for more than 40 hours straight",
    "<b>Personal:</b>\nHad to put an animal down (example: hit with car - still alive but barely and put it down)",
    "<b>Personal:</b>\nGotten drunk and vomited somewhere not in a toilet or sink",
    "<b>Personal:</b>\nBeen to Juvie, Jail, rehab or a mental ward",
    "<b>Personal:</b>\nFlirted my way out of a ticket or tried to",
    "<b>Personal:</b>\nEavesdropped on something and ended up scarred for life",
    "<b>Personal:</b>\nCut a cat's whiskers",
    "<b>Personal:</b>\nBeen a pyromaniac",
    "<b>Personal:</b>\nThe designated driver",
    "<b>Personal:</b>\nBelieved in a code of conduct (Exampe: Don't f*ck a friend's girl, etc.)",
    "<b>Personal:</b>\nBelieved if I drink the last of the booze I buy the next pack or bottle",
    "<b>Personal:</b>\nHumiliated someone",
    "<b>Personal:</b>\nDone something that got my friend in trouble",
    "<b>Personal:</b>\nSh*t myself",
    "<b>Personal:</b>\nGone skinny dipping with someone or with people",
    "<b>Personal:</b>\nDriven a car naked or topless",
    "<b>Personal:</b>\nTried to get out of a situation because I felt there was nothing left to talk about",
    "<b>Personal:</b>\nFlashed someone",
    "<b>Personal:</b>\nOwned a copy of the Anarchist Cook Book and used at least one recipe",
    "<b>Personal:</b>\nFormed a Blood Pact",
    "<b>Personal:</b>\nConsidered or got plastic surgery",
    "<b>Personal:</b>\nGot into a random fight",
    "<b>Personal:</b>\nWanted to murder someone",
    "<b>Personal:</b>\nTripped someone who's pregnant or elderly on purpose",
    "<b>Personal:</b>\nGiven 100 dollars or more to a homeless person",
    "<b>Personal:</b>\nSent nudes to the wrong person",
    "<b>Personal:</b>\nBeen to a concert",
    "<b>Personal:</b>\nClogged a toilet in a public restroom",
    "<b>Personal:</b>\nBeen crossfaded or high on two or more drugs",
    "<b>Personal:</b>\nAte more than I was told of anything made with weed",
    "<b>Personal:</b>\nStared at a drive through menu while high and forgot if I ordered",
    "<b>Personal:</b>\nBeen arrested, fined, or convicted of something",
    "<b>Personal:</b>\nSnuck into a building or event",
    "<b>Personal:</b>\nTried moonshine (american white whiskey brewed in the woods)",
    "<b>Personal:</b>\nDrank before I turned 21",
    "<b>Personal:</b>\nDrank a body shot",
    "<b>Personal:</b>\nDrank a flaming shot",
    "<b>Personal:</b>\nPlayed strip poker",
    "<b>Personal:</b>\nGot my nipples and or genitals pierced",
    "<b>Personal:</b>\nHired a stripper, hooker, escort, etc. for a party",
    "<b>Personal:</b>\nKilled someone",
    "<b>Personal:</b>\nGave up on friends and or family in order to make myself better",
    "<b>Personal:</b>\nBeen tased or pepper sprayed",
    "<b>Personal:</b>\nBeen sh*t or p*ssed on by an animal",
    "<b>Personal:</b>\nBeen a part of a Live Action Role Play (furries do not count, war re-enactments, dungeons and dragons do count)",
    "<b>Personal:</b>\nBeen kicked off a team",
    "<b>Personal:</b>\nUsed a game's stats and or rare items to flirt with someone",
    "<b>Personal:</b>\nCaught something on fire while trying to cook",
    "<b>Personal:</b>\nQuestioned who was better for a Superhero's city like Batman or Joker",
    "<b>Personal:</b>\nCried over a comic",
    "<b>Personal:</b>\nPretended to know someone I did not know",
    "<b>Personal:</b>\nBeen a wing man and successful",
    "<b>Personal:</b>\nFelt out of touch with pop culture",
    "<b>Personal:</b>\nHad 1GB internet in my residency",
    "<b>Personal:</b>\nGiven someone a sex hotline number to avoid them calling me",
    "<b>Personal:</b>\nGiven someone the suicide hotline number to avoid them calling me",
    "<b>Personal:</b>\nCovered for a friend financially and expected nothing in return",
    "<b>Personal:</b>\nTalked sh*t behind someone's back",
    "<b>Personal:</b>\nBeen high and just stared at lights or Christmas lights",
    "<b>Personal:</b>\nBeen the drunk philosopher",
    "<b>Personal:</b>\nRolled a joint with the Holy Bible",
    "<b>Personal:</b>\nBought porn of any form",
    "<b>Personal:</b>\nSubscribed to someone's Patreon",
    "<b>Personal:</b>\nLed someone on",
    "<b>Personal:</b>\nCared about the titles to my porn",
    "<b>Personal:</b>\nMasturbated and came in under 1 minute",
    "<b>Personal:</b>\nOwned a body pillow",
    "<b>Personal:</b>\nWatched a gift I got someone be disregarded as nothing",
    "<b>Personal:</b>\nBeen part of a cult",
    "<b>Personal:</b>\nExperienced something paranormal",
    "<b>Personal:</b>\nExperienced my worst fear",
    "<b>Personal:</b>\nPassed out with porn playing",
    "<b>Personal:</b>\nSpent more than 1,000 dollars at a strip club",
    "<b>Personal:</b>\nBeen caught talking about someone and that person was behind me",
    "<b>Personal:</b>\nShared my porn with someone",
    "<b>Personal:</b>\nSh*t posted on P*rnHub",
    "<b>Personal:</b>\nHeld a grudge for a year or longer",
    "<b>Personal:</b>\nOrganized my porn collection",
    "<b>Personal:</b>\nHad more than 50GB of porn (no videos allowed)",
    "<b>Personal:</b>\nPirated a porn video that was over an hour long",
    "<b>Personal:</b>\nI have experienced road rage and was the one to get out of the car first",
    "<b>Personal:</b>\nSpent more than an hour trying to find a specific porno",
    "<b>Personal:</b>\nUsed someone for my own personal gain",
    "<b>Personal:</b>\nWatched porn at max volume",
    "<b>Personal:</b>\nERPed in Minecraft and or Roblox",
    "<b>Personal:</b>\nHad sex with a stuffed animal to thrill a furry or beastiaity fetish",
    "<b>Personal:</b>\nHad a porn stash that consists of only pictures and totals out to 1GB or more",
    "<b>Personal:</b>\nHad a porn stash that consists of only videos and totals out to 10GB or more",
    "<b>Personal:</b>\nHad a family ran joke",
    "<b>Personal:</b>\nBeen turned on by a telemarketer",
    "<b>Personal:</b>\nHad to submit proof a sex toy was broken",
    // }},
    // {"Gaming", new[] {
    "<b>Gaming:</b>\nSpent more than 1,000 dollars in a video game in 1 year",
    "<b>Gaming:</b>\nSpent more than 4,000 dollars in a video game over its lifetime",
    "<b>Gaming:</b>\nBacked a game for more than 2,000 dollars",
    "<b>Gaming:</b>\nOwned more than 1 top tier founder pack (examples: Warframe, Firefall, ArcheAge, Tera, etc.)",
    "<b>Gaming:</b>\nHacked or modded in a game be it save game editing, aimbotting, currency manipulation, etc.",
    "<b>Gaming:</b>\nPlayed a single game for more than 48 hours straight",
    "<b>Gaming:</b>\nP*ssed in a bottle to avoid leaving a game",
    "<b>Gaming:</b>\nActually used P2W options",
    "<b>Gaming:</b>\nOwned more than one copy of Skyrim, Minecraft, PUBG, and or Fortnite",
    "<b>Gaming:</b>\nRoleplayed in an MMORPG",
    "<b>Gaming:</b>\nBeen invovled in erotic roleplay in an MMORPG",
    "<b>Gaming:</b>\nLooked for a game's porn",
    "<b>Gaming:</b>\nBeen so toxic I made someone rage quit",
    "<b>Gaming:</b>\nRage quit a game",
    "<b>Gaming:</b>\nCared about game visual fidelity over game quality",
    "<b>Gaming:</b>\nGot an ace clutch",
    "<b>Gaming:</b>\nManipulated someone into saying something that got them punished by their parents",
    "<b>Gaming:</b>\nBeen the racist sore loser (lost to a german kid and called him a camping nazi)",
    "<b>Gaming:</b>\nWatched people doing erotic roleplay",
    "<b>Gaming:</b>\nDone something to avoid getting kicked for being AFK",
    "<b>Gaming:</b>\nKicked someone out of my clan or guild for a laugh",
    "<b>Gaming:</b>\nHad sex with a Clan mate or Guildie",
    "<b>Gaming:</b>\nStole from a Clan or Guild I was in",
    "<b>Gaming:</b>\nPlanned a coup against my Clan Leader or Guild Master (took someone out of power)",
    "<b>Gaming:</b>\nBought and or sold an in game currency",
    "<b>Gaming:</b>\nCrashed an aerial vehicle killing everyone in it, but not my designated target",
    "<b>Gaming:</b>\nEjected from an aerial vehicle and killed everyone in it as it crashed",
    "<b>Gaming:</b>\nWatched someone so bad or new to a video game I couldn't help but to back seat them",
    "<b>Gaming:</b>\nBeen so mad at a game that I broke something",
    "<b>Gaming:</b>\nHurt someone over a game intentionally",
    "<b>Gaming:</b>\nHurt someone while playing a game accidentally",
    "<b>Gaming:</b>\nLost or removed someone as a friend due to a game",
    "<b>Gaming:</b>\nBeen an elitist (you play the highest ranks and do not associate with noobs)",
    "<b>Gaming:</b>\nBeen a pro player or in a games highest ranks",
    "<b>Gaming:</b>\nGot an ace",
    "<b>Gaming:</b>\nStabbed more than three people within 10 seconds",
    "<b>Gaming:</b>\nGot a nuke in any Call of Duty Game",
    "<b>Gaming:</b>\nGone full 9/11 or Kamikaze while in a jet or plane",
    "<b>Gaming:</b>\nWent positive in a game doing nothing but suicide bombings",
    "<b>Gaming:</b>\nTook a game way too seriously",
    "<b>Gaming:</b>\nEnjoyed playing casually",
    "<b>Gaming:</b>\nWanted full body tracking for anything other than sex",
    "<b>Gaming:</b>\nPlayed or watched VR porn or a video game",
    "<b>Gaming:</b>\nConsidered or tried to become a streamer or youtube creator",
    "<b>Gaming:</b>\nGot a 1 in 1 million kill",
    "<b>Gaming:</b>\nHad a legit username (Examples: Reaper, Ambulance, Doctor, Hardcore, etc.)",
    "<b>Gaming:</b>\nHeard some sh*t go down over an open mic",
    "<b>Gaming:</b>\nF*cked up so bad I committed seppuku",
    "<b>Gaming:</b>\nBeen a dungeon, trial or raid leader",
    "<b>Gaming:</b>\nBeen a main tank and or healer",
    "<b>Gaming:</b>\nBeen into the Fallout series or the Elder Scrolls series",
    "<b>Gaming:</b>\nBeen into the Mass Effect Series or Dragon Age series",
    "<b>Gaming:</b>\nBeen into FPS games or RPG games",
    "<b>Gaming:</b>\nGotten five stars in GTA V and lasted longer than an hour while not trying to lose the cops",
    "<b>Gaming:</b>\nExploited a game breaking bug, feature, or exploit to my own advantage",
    "<b>Gaming:</b>\nBought and or sold an account",
    "<b>Gaming:</b>\nConsidered, tried, or did become a cam model or pornstar in order to get a larger following on youtube or as a streamer",
    "<b>Gaming:</b>\nWon any money or a trophy or title in a video game",
    "<b>Gaming:</b>\nPlayed a game since Beta and watched it die (server shut down only)",
    "<b>Gaming:</b>\nPlayed a single game for more than 80 hours in a week",
    "<b>Gaming:</b>\nPlayed a single game for more than 1,000 hours",
    "<b>Gaming:</b>\nPlayed a single game for more than 5,000 hours",
    "<b>Gaming:</b>\nSuicided my whole team whom I've never met before for sh*ts and giggles",
    "<b>Gaming:</b>\nHad a friend so sh*t at a game I stopped playing with them",
    "<b>Gaming:</b>\nGotten a 2 or more kills with a martyrdom grenade (nade drops after your death and you get kills)",
    "<b>Gaming:</b>\nPlayed Hide And Seek in Dark Souls",
    "<b>Gaming:</b>\nGotten a kill in a game via Spartan Kick",
    "<b>Gaming:</b>\nBegged for an in game currency or power leveling",
    "<b>Gaming:</b>\nStreamed to literally no one for longer than an hour",
    "<b>Gaming:</b>\nStreamed for 24 hours straight",
    "<b>Gaming:</b>\nMade a friend, known them for over a year only to see them never log in again",
    "<b>Gaming:</b>\nKicked someone for failing to clutch",
    "<b>Gaming:</b>\nSold a rare skin or item for over 419 dollars",
    "<b>Gaming:</b>\nPlayed a game that deeply scared me",
    "<b>Gaming:</b>\nSaved a game and committed atrocities even Hitler would question",
    "<b>Gaming:</b>\nPlayed games as a coping method",
    "<b>Gaming:</b>\nFelt extremely let down by a game I badly wanted",
    "<b>Gaming:</b>\nWatched streamers or youtube videos in order to get a better understanding of a game",
    "<b>Gaming:</b>\nLet a party, group, raid, etc. wipe over one person",
    "<b>Gaming:</b>\nPlayed a board game that I deeply enjoyed",
    "<b>Gaming:</b>\nTop fragged and won with a total kill amount equal to or greater than the rest of my whole team combined",
    "<b>Gaming:</b>\nSkipped school to play a game",
    "<b>Gaming:</b>\nNinja looted something",
    "<b>Gaming:</b>\nNinja looted or need rolled and won something that I absolutely could not use or benefit from just to troll",
    "<b>Gaming:</b>\nEnjoyed the Final Fantasy series",
    "<b>Gaming:</b>\nLoved a game mechanic more than anything else but hated the rest of the game (Best example: Dying Light - great movement, bad game)",
    "<b>Gaming:</b>\nCared more for FPS than graphic quality",
    "<b>Gaming:</b>\nBeen a coach or mentor in a game",
    "<b>Gaming:</b>\nBeen coached or mentored in a game",
    "<b>Gaming:</b>\nCared more for PvP than PvE",
    "<b>Gaming:</b>\nWatched a streamer for more than 5 hours",
    "<b>Gaming:</b>\nPlayed against or with a hacker",
    "<b>Gaming:</b>\nBelieved people under the age of 18 should not be able to play certain games",
    "<b>Gaming:</b>\nDisconnected a game in order to save face, K/D, or W/L",
    "<b>Gaming:</b>\nPirated a game",
    "<b>Gaming:</b>\nWon 5 games in a row",
    "<b>Gaming:</b>\nHad a K/D or W/L of or over 2.0",
    "<b>Gaming:</b>\nGot an ace that was from explosives or headshots only",
    "<b>Gaming:</b>\nPut an explosive on or around someone without them finding out and killed them with it",
    "<b>Gaming:</b>\nUsed a vehicle with explosives on it and waited for the enemy to take it and waited for longer than 30 seconds to explode it",
    "<b>Gaming:</b>\nPre-ordered a game",
    "<b>Gaming:</b>\nBought a Collector's Edition of a game",
    "<b>Gaming:</b>\nI have bought something someone else uses with the thought that I could be better with it",
    "<b>Gaming:</b>\nI have donated more than 100 dollars to a streamer",
    "<b>Gaming:</b>\nI have raided or hosted a streamer with 100 or more viewers",
    "<b>Gaming:</b>\nWatched a streamer who had no viewers",
    "<b>Gaming:</b>\nPlayed a game that has lived for longer than five years",
    "<b>Gaming:</b>\nPlayed a game since Alpha",
    "<b>Gaming:</b>\nPlayed a game on it's test server",
    "<b>Gaming:</b>\nPlayed games above 1080p",
    "<b>Gaming:</b>\nCreated mods for a game like DayZ, Minecraft, Rust, Unturned, etc.",
    "<b>Gaming:</b>\nWorked in game development in any form",
    "<b>Gaming:</b>\nPlayed an RTS game as a God and lived only to conquer",
    "<b>Gaming:</b>\nPlayed a Sims game and actively tried to not kill anyone",
    "<b>Gaming:</b>\nBeen invested in a game or game series that I owned several offset products to it (World of warcraft books, etc.)",
    "<b>Gaming:</b>\nBuilt a PC that cost 3,000 dollars or less",
    "<b>Gaming:</b>\nPlanned to murder whoever it was that made the first escort mission",
    "<b>Gaming:</b>\nWanted to play something but was denied because my PC couldn't run it",
    "<b>Gaming:</b>\nBeen called out, kicked, or sh*t on for not having a mic in a game",
    "<b>Gaming:</b>\nWatched youtube meme videos for a game",
    "<b>Gaming:</b>\nPlayed an indie game, loved it and recommend it (which game?)",
    "<b>Gaming:</b>\nPlayed an adult game like 3DXChat, Bonecraft, Hentai Heroes, etc.",
    "<b>Gaming:</b>\nMade a real girlfriend or boyfriend in a game",
    "<b>Gaming:</b>\nHosted a game",
    "<b>Gaming:</b>\nHosted a rented server",
    "<b>Gaming:</b>\nPassed out while gaming",
    "<b>Gaming:</b>\nUsed 2 or more monitors",
    "<b>Gaming:</b>\nOwned a mechanical keyboard and or a mouse with weights",
    "<b>Gaming:</b>\nBeen in a top tier Guild or Clan",
    "<b>Gaming:</b>\nPlayed Tera, EVE Online, World of Warcraft, Guild Wars, ArcheAge, Black Desert Online, Elder Scrolls Online, EverQuest, RuneScape, DnD: Neverwinter, Perfect World, or Maple Story",
    "<b>Gaming:</b>\nPlayed Minecraft in Hardcore and lived longer than 666 days",
    "<b>Gaming:</b>\nPlayed Minecraft and been blown off or knocked off a cliff and died",
    "<b>Gaming:</b>\nTricked someone into doing something",
    "<b>Gaming:</b>\nPlayed a PC game with a controller",
    "<b>Gaming:</b>\nBeen a Guild Master or Officer or a Clan Leader or Clan Officer",
    "<b>Gaming:</b>\nBeen forced into being a casual gamer because life caught up",
    "<b>Gaming:</b>\nGamed on a laptop",
    "<b>Gaming:</b>\nBeen to a gaming related convention",
    "<b>Gaming:</b>\nPlayed Star Citizen",
    "<b>Gaming:</b>\nHated casual gamers",
    "<b>Gaming:</b>\nBelieved I play games better when intoxicated",
    "<b>Gaming:</b>\nBeen part of a drinking game while in a video game",
    "<b>Gaming:</b>\nPrior to dying an epic or stupid death yelled \"Witness me!\"",
    "<b>Gaming:</b>\nBought hacks and or mods for a game",
    "<b>Gaming:</b>\nEnjoyed a show or movie based on a game",
    "<b>Gaming:</b>\nStopped playing a game due to an update I couldn't stand",
    "<b>Gaming:</b>\nPlayed a game I hated because my friends love it",
    "<b>Gaming:</b>\nPlayed WoW Classic only to find out it wasn't what I had hoped for",
    "<b>Gaming:</b>\nBeen part of a Guild and or Clan war",
    "<b>Gaming:</b>\nMade it to the currency cap in an MMORPG in a single day",
    "<b>Gaming:</b>\nMade money from selling a service in a game",
    "<b>Gaming:</b>\nHad a sh*tty or insane Guild Master and or Clan Leader",
    "<b>Gaming:</b>\nWanted to be an eSports fan",
    "<b>Gaming:</b>\nPlayed a game that I wanted to enjoy but the game was so bad I couldn't (Ex: Mass Effect Andromeda)",
    "<b>Gaming:</b>\nPlayed a version of strip poker using video games",
    "<b>Gaming:</b>\nBeen so invested into a game I could tell you the lore to genuinely everything",
    "<b>Gaming:</b>\nPlayed a game that was based on a show or movie",
    "<b>Gaming:</b>\nCreated a comic, fan fict, and or manga for a game",
    "<b>Gaming:</b>\nCosplayed as video game character or designed an outfit based for one",
    "<b>Gaming:</b>\nBeen elite checked by a game (going from WoW to ESO and not knowing wtf to do and how)",
    "<b>Gaming:</b>\nBeen hard gear checked while PvPing (got into a match you thought you'd win and got demolished)",
    "<b>Gaming:</b>\nHad to remove an Officer in my Clan or Guild for their behavior and or actions",
    "<b>Gaming:</b>\nPlayed an FPS with actual military or police strategy and dominated",
    "<b>Gaming:</b>\nPlayed a Military Simulator and got my *ss handed to me",
    "<b>Gaming:</b>\nBeen griefed to the point I gave up on the server and or game",
    "<b>Gaming:</b>\nGriefed someone so bad they rage quit",
    "<b>Gaming:</b>\nPlayed a game that I played when I was a kid only to find out it was actually trash now",
    "<b>Gaming:</b>\nStruggled on a boss in a game that took longer than a month to down",
    "<b>Gaming:</b>\nUsed hacks, mods, and or cheats against another hacker using them maliciously",
    "<b>Gaming:</b>\nPretended to be an Admin or GM in a game to scam someone",
    "<b>Gaming:</b>\nUsed a video game guide book",
    // }},
    // {"Music", new[] {
    "<b>Music:</b>\nPlayed a wind instrument",
    "<b>Music:</b>\nPlayed a percussion instrument",
    "<b>Music:</b>\nPlayed a string instrument",
    "<b>Music:</b>\nPlayed a keyboard instrument",
    "<b>Music:</b>\nSang in a choir",
    "<b>Music:</b>\nBeen a lead singer",
    "<b>Music:</b>\nSang in a duet",
    "<b>Music:</b>\nPlayed a solo piece in any form",
    "<b>Music:</b>\nPlayed or sang on stage",
    "<b>Music:</b>\nPlayed or sang at a professional event",
    "<b>Music:</b>\nLoved all forms of music and meant it",
    "<b>Music:</b>\nBeen to a music festival",
    "<b>Music:</b>\nBeen to a concert at an arena or major stage",
    "<b>Music:</b>\nBeen to a rave",
    "<b>Music:</b>\nBeen labeled a punk",
    "<b>Music:</b>\nBeen labeled a metal head",
    "<b>Music:</b>\nBeen labeled as EMO",
    "<b>Music:</b>\nBeen labeled as Goth",
    "<b>Music:</b>\nBeen a Juggalo",
    "<b>Music:</b>\nBelieved music cannot save lives",
    "<b>Music:</b>\nNot loved a video game's music",
    "<b>Music:</b>\nUsed my musical talent in a professional setting",
    "<b>Music:</b>\nFormed a band orchestra and made over 10,000 dollars performing",
    "<b>Music:</b>\nBeen recruited for a band or orchestra",
    "<b>Music:</b>\nTaught someone how to play an instrument",
    "<b>Music:</b>\nMade an instrument",
    "<b>Music:</b>\nPlayed an electric instrument",
    "<b>Music:</b>\nPlayed an acoustic instrument",
    "<b>Music:</b>\nBeen a street performer with my instrument",
    "<b>Music:</b>\nDressed in scene gear",
    "<b>Music:</b>\nLiked mumble rap",
    "<b>Music:</b>\nListened to underground rap",
    "<b>Music:</b>\nListened to real gangster or Narco rap",
    "<b>Music:</b>\nListened to Outlaw Country",
    "<b>Music:</b>\nListened to Comedy Songs",
    "<b>Music:</b>\nSang Karaoke",
    "<b>Music:</b>\nHad a song for every emotion or feeling",
    "<b>Music:</b>\nFelt deeply touched by music",
    "<b>Music:</b>\nEnjoyed an anime's music",
    "<b>Music:</b>\nListened to stoner rock or rap while stoned",
    "<b>Music:</b>\nListened to Nightcore",
    "<b>Music:</b>\nListened to Lo-Fi",
    "<b>Music:</b>\nMade a playlist that has over 200 songs in it",
    "<b>Music:</b>\nMade a playlist based in one genre of music",
    "<b>Music:</b>\nBeen complimented about my musical taste",
    "<b>Music:</b>\nBeen able to show people music they knew but had forgotten",
    "<b>Music:</b>\nHad a guilty pleasure song, artist, or genre",
    "<b>Music:</b>\nSeen an episode of Epic Rap Battles",
    "<b>Music:</b>\nBeen able to free style (absolutely requires 6 bars for proof on the spot)",
    "<b>Music:</b>\nBeen a real groupie (you would absolutely given the chance f*ck a music artist/group)",
    "<b>Music:</b>\nBeen a roadie (you went on tour with a band, group, artist)",
    "<b>Music:</b>\nOwned a VIP or Back Stage Access Pass to a concert",
    "<b>Music:</b>\nSpent more than 500 dollars at a concert (Tickets and VIP stuff does not count)",
    "<b>Music:</b>\nBeen in a mosh pit",
    "<b>Music:</b>\nTaught myself an instrument",
    "<b>Music:</b>\nBeen able to read music (if you can, move)",
    "<b>Music:</b>\nEnjoyed a remix more than original",
    "<b>Music:</b>\nMade my own playlist because a game's stock music was bad",
    // }},
    // {"Who Hasn't", new[] {
    "<b>Who Hasn't:</b>\nPut my finger into a pet's mouth while yawning",
    "<b>Who Hasn't:</b>\nLicked my fingers after eating food",
    "<b>Who Hasn't:</b>\nCreated a fake account",
    "<b>Who Hasn't:</b>\nEaten food in a supermarket without purchasing",
    "<b>Who Hasn't:</b>\nRode in a shopping cart",
    "<b>Who Hasn't:</b>\nTried to sleep with my eyes open",
    "<b>Who Hasn't:</b>\nSpoke to my pets about the purpose of life",
    "<b>Who Hasn't:</b>\nSpoke with food in my mouth",
    "<b>Who Hasn't:</b>\nScreamed when I saw a spider, bug, or rodent",
    "<b>Who Hasn't:</b>\nBroken something at my friend's house and did not tell them about it",
    "<b>Who Hasn't:</b>\nEaten dog or cat food",
    "<b>Who Hasn't:</b>\nTried to put a light bulb into my mouth",
    "<b>Who Hasn't:</b>\nWorn socks with holes",
    "<b>Who Hasn't:</b>\nAdded Mentos to Coca-Cola",
    "<b>Who Hasn't:</b>\nLooked through a telescope at the stars",
    "<b>Who Hasn't:</b>\nGone outside in pajamas",
    "<b>Who Hasn't:</b>\nSkipped hand washing after going to the toilet",
    "<b>Who Hasn't:</b>\nFallen asleep in a movie theather",
    "<b>Who Hasn't:</b>\nDreamed of changing appearances with my girlfriend/boyfriend",
    "<b>Who Hasn't:</b>\nEaten a whole pizza alone",
    "<b>Who Hasn't:</b>\nFallen asleep in the sun and got burned",
    "<b>Who Hasn't:</b>\nTold my friend's joke but took the credit",
    "<b>Who Hasn't:</b>\nFallen from a ladder",
    "<b>Who Hasn't:</b>\nLaughed at the most inappropriate moment",
    "<b>Who Hasn't:</b>\nRan away from a paranormal phenomena",
    "<b>Who Hasn't:</b>\nPlayed pranks on someone on the 1st April",
    "<b>Who Hasn't:</b>\nBeen afraid of clowns",
    "<b>Who Hasn't:</b>\nGoogled my full name to know the search results",
    "<b>Who Hasn't:</b>\nForgot the name of a person I just met",
    "<b>Who Hasn't:</b>\nFled a restaurant without paying",
    "<b>Who Hasn't:</b>\nCalled my friend by a wrong name",
    "<b>Who Hasn't:</b>\nSworn to say the truth when I was actually telling the lie",
    "<b>Who Hasn't:</b>\nRe-gifted a present that I did not like",
    "<b>Who Hasn't:</b>\nPracticed yoga or cross fit",
    "<b>Who Hasn't:</b>\nChanged a baby's diaper",
    "<b>Who Hasn't:</b>\nSleepwalked",
    "<b>Who Hasn't:</b>\nListened to the same song on repeat for more than a week",
    "<b>Who Hasn't:</b>\nDrank in a bar for somebody's account all night long",
    "<b>Who Hasn't:</b>\nPretended to be busy to avoid meeting with somebody",
    "<b>Who Hasn't:</b>\nStood in the rain without an umbrella",
    "<b>Who Hasn't:</b>\nThrown my phone at the wall",
    "<b>Who Hasn't:</b>\nPlayed Pokemon Go",
    "<b>Who Hasn't:</b>\nActually used any of YouTube life hacks",
    "<b>Who Hasn't:</b>\nFeared a monster that lives under my bed",
    "<b>Who Hasn't:</b>\nMade a snow angel",
    "<b>Who Hasn't:</b>\nBeen secretly in love with my school teacher",
    "<b>Who Hasn't:</b>\nSmoked in a school toilet room",
    "<b>Who Hasn't:</b>\nBeen afraid of the darkness",
    "<b>Who Hasn't:</b>\nGone for night diving",
    "<b>Who Hasn't:</b>\nBeen chased by a dog or a cat",
    "<b>Who Hasn't:</b>\nGot a piercing",
    "<b>Who Hasn't:</b>\nHidden cigarettes, drugs, or booze from my parents",
    "<b>Who Hasn't:</b>\nWanted to have children",
    "<b>Who Hasn't:</b>\nSlept without underwear",
    "<b>Who Hasn't:</b>\nFallen in love with someone I met online",
    "<b>Who Hasn't:</b>\nGifted somebody a hand-made Valentine's Day card",
    "<b>Who Hasn't:</b>\nBeen in a long distance relationship",
    "<b>Who Hasn't:</b>\nTaken the first step to making peace after a fight",
    "<b>Who Hasn't:</b>\nRemained blind to my partner's faults",
    "<b>Who Hasn't:</b>\nSpent the night at my significant other's house",
    "<b>Who Hasn't:</b>\nDated someone my parents did not approve",
    "<b>Who Hasn't:</b>\nForgiven a betrayal",
    "<b>Who Hasn't:</b>\nPretended to be kind to people who I actually despised",
    "<b>Who Hasn't:</b>\nLaughed at someone's misfortune",
    "<b>Who Hasn't:</b>\nWanted to hack someone's account in a social media and read the messages",
    "<b>Who Hasn't:</b>\nLost faith in humanity",
    "<b>Who Hasn't:</b>\nRegretted something I did",
    "<b>Who Hasn't:</b>\nFelt guilty for hurting someone",
    "<b>Who Hasn't:</b>\nFallen into the same trap twice",
    "<b>Who Hasn't:</b>\nFell while rollerblading or skating",
    "<b>Who Hasn't:</b>\nWanted to change something in my past",
    "<b>Who Hasn't:</b>\nStayed awake late with someone on my mind",
    "<b>Who Hasn't:</b>\nSat naked on leather",
    "<b>Who Hasn't:</b>\nNetflixed and chilled",
    "<b>Who Hasn't:</b>\nSent a sext",
    "<b>Who Hasn't:</b>\nTaken a bathroom selfie",
    "<b>Who Hasn't:</b>\nGiven my phone number to someone I just met",
    "<b>Who Hasn't:</b>\nRan into a pole and or wall",
    "<b>Who Hasn't:</b>\nSlipped on ice",
    "<b>Who Hasn't:</b>\nFailed to judge how deep a puddle was",
    "<b>Who Hasn't:</b>\nUsed the wrong bathroom",
    "<b>Who Hasn't:</b>\nWalked in or had someone walk in on me in the bathroom",
    "<b>Who Hasn't:</b>\nFound a wallet",
    "<b>Who Hasn't:</b>\nLost something that was on me or in a different pocket in my clothes",
    "<b>Who Hasn't:</b>\nBit my tongue, lip and or cheek and made it bleed",
    "<b>Who Hasn't:</b>\nWatched a podcast",
    // }},
    // {"Intoxicated", new[] {
    "<b>Intoxicated:</b>\nBeen to the point I'm on the roulette table (world spinning)",
    "<b>Intoxicated:</b>\nBeen the blackout drunk who has done awful sh*t",
    "<b>Intoxicated:</b>\nEmotional drunk who can't stop crying",
    "<b>Intoxicated:</b>\nP*ssed drunk who just wants to fight the world",
    "<b>Intoxicated:</b>\nBeen the drunken philosopher",
    "<b>Intoxicated:</b>\nStolen something while intoxicated from a house party",
    "<b>Intoxicated:</b>\nDone a pub crawl (bar hopping to get as hammered as possible)",
    "<b>Intoxicated:</b>\nThought I could handle cocktails better",
    "<b>Intoxicated:</b>\nP*ssed on a building or car that was not mine while intoxicated",
    "<b>Intoxicated:</b>\nTaken a sh*t in someone's yard while intoxicated",
    "<b>Intoxicated:</b>\nBeen caught taking a p*ss or sh*t outside while intoxicated",
    "<b>Intoxicated:</b>\nHad a trip so bad it haunts me to this day",
    "<b>Intoxicated:</b>\nTripped out so hard I lost my mind",
    "<b>Intoxicated:</b>\nBeen so high I went full on Moth mode (just stared at lights HAND OVER THE LAMP)",
    "<b>Intoxicated:</b>\nBeen the affectionate one while intoxicated (super touchy, flirty or outright down to f*ck)",
    "<b>Intoxicated:</b>\nBeen the functioning type while intoxicated (you can do actual work that requires math and or focus to do)",
    "<b>Intoxicated:</b>\nStarted an orgy because I started having sex in a very public room while intoxicated",
    "<b>Intoxicated:</b>\nVomited in someone's mouth while intoxicated",
    "<b>Intoxicated:</b>\nVomited while having sex with someone from being intoxicated",
    "<b>Intoxicated:</b>\nPrayed to the Almighty Porcelain for sanctuary and painless cold",
    "<b>Intoxicated:</b>\nSeen someone who was way passed the line and do something insane",
    "<b>Intoxicated:</b>\nBeen so high the paranoia set in",
    "<b>Intoxicated:</b>\nBeen so high and had to walk home and completely couldn't remember where the f*ck I am or going",
    "<b>Intoxicated:</b>\nBeen so high I could hear the blood pumping in my body and scared myself when it stopped",
    "<b>Intoxicated:</b>\nBeen so intoxicated I thought my heart or lungs were about to fail",
    "<b>Intoxicated:</b>\nBeen so high I went to a mall and while coming out began to panic because I had no idea where I parked and searched for over 30 minutes",
    "<b>Intoxicated:</b>\nBeen cross faded into a new dimension",
    "<b>Intoxicated:</b>\nHad a trip so eye opening I believed I had the answers",
    "<b>Intoxicated:</b>\nTripped so bad it genuinely changed my life",
    "<b>Intoxicated:</b>\nTripped and rode on a swing or drove a car",
    "<b>Intoxicated:</b>\nFelt the weight of Earth's gravity",
    "<b>Intoxicated:</b>\nStolen something while intoxicated that was a prized item",
    "<b>Intoxicated:</b>\nP*ssed someone off because I stock piled munchies",
    "<b>Intoxicated:</b>\nOpened the fridge and only found sadness to stare back at me",
    "<b>Intoxicated:</b>\nSober up in a nano second because some sh*t just got too damn real",
    "<b>Intoxicated:</b>\nBolted from a house naked while intoxicated because I was about to be shot while intoxicated",
    "<b>Intoxicated:</b>\nTried to stand up only to face plant into the ground",
    "<b>Intoxicated:</b>\nCompletely abandoned someone or thing because I smelled some good food while intoxicated",
    "<b>Intoxicated:</b>\nF*cked someone sober up when I woke up and found out I f*cked a troll",
    "<b>Intoxicated:</b>\nF*cked someone sober up when I woke up and found out I was the troll",
    "<b>Intoxicated:</b>\nWoke up with a hang over and the first thought I had was to go pray to the Porcelain God",
    "<b>Intoxicated:</b>\nHad the cops called on a party I was at while intoxicated",
    "<b>Intoxicated:</b>\nBeen high for an entire 24 hours",
    "<b>Intoxicated:</b>\nBeen high for an entire week without sobering up at all",
    "<b>Intoxicated:</b>\nEaten way too much of an edible",
    "<b>Intoxicated:</b>\nDowned a whole rack of edibles without the knowledge they were",
    "<b>Intoxicated:</b>\nBeen so intoxicated I forgot I was having sex with someone",
    "<b>Intoxicated:</b>\nDriven a car while high and felt like I always going light speed but when I looked I wasn't even going 30mph",
    "<b>Intoxicated:</b>\nRaged out and lost my mind while high",
    "<b>Intoxicated:</b>\nBeen strung out with the scratches",
    "<b>Intoxicated:</b>\nDone more than two types of drugs inside of 24 hours",
    "<b>Intoxicated:</b>\nHad to sober up in a detox tank",
    "<b>Intoxicated:</b>\nBeen seriously injured while intoxicated"
    // }}
  };
  
  public void Start() {
    Debug.Log(questions.Length + " Total Questions loaded (NHIE)");
    masterToggle.isOn = masterLocked;
  }
  public override void OnDeserialization() {
    if (previousText != currentText) {
      Debug.Log("NHIE updated: " + currentText + " " + (currentText < 0 ? "" : questions[currentText]));
    }
    if (masterToggle.isOn != masterLocked) {
      Debug.Log("NHIE Master Lock: " + masterLocked + " (am master: " + Networking.LocalPlayer.isMaster + ")");
    }
    previousText = currentText;
    if (currentText >= 0) {
      textBox.text = questions[currentText];
    } else if (currentText == -1) {
      textBox.text = "Played \"Never Have I Ever\"";
    } else {
      textBox.text = "";
    }
    masterToggle.isOn = masterLocked;
  }
  public void Update() {
    if (masterToggle.isOn != masterLocked) {
      masterToggle.isOn = masterLocked;
    }
  }
  public void ClickedRandom() {
    if (masterLocked && !Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    previousText = currentText = Random.Range(0, questions.Length);
    if (currentText >= 0) {
      textBox.text = questions[currentText];
    } else if (currentText == -1) {
      textBox.text = "Played \"Never Have I Ever\"";
    } else {
      textBox.text = "";
    }
    RequestSerialization();
  }
  public void ClickedClear() {
    if (masterLocked && !Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    textBox.text = "";
    previousText = currentText = -2;
    RequestSerialization();
  }
  public void ToggleMasterLock() {
    Debug.Log("Toggling Master Lock: I am Master (" + Networking.LocalPlayer.isMaster + "), currently (" + masterLocked + ")");
    if (!Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    masterLocked = !masterLocked;
    // masterToggle.isOn = masterLocked;
    Debug.Log("Toggling Master Lock Updated to (" + masterLocked + ")");

    RequestSerialization();
    if (clickSound != null) clickSound.PlayOneShot(clickSound.clip, 1.0f);
  }
}
