using UdonSharp;
using UnityEngine;
using VRC.SDKBase;
using VRC.Udon;
using UnityEngine.UI;
using System.Collections.Generic;

public class NHIEQuestions : UdonSharpBehaviour {
  public Text textBox;
  public Text usernameText;
  public Toggle masterToggle;
  public AudioSource clickSound;
  [UdonSynced] public int currentText = -1;
  [UdonSynced] public string currentUsername = "";
  public int previousText = -1;
  [UdonSynced] public bool masterLocked = false;

  string[] questions = new[] {
    "<b>Lewd:</b>\nCheated on a partner.",
    "<b>Lewd:</b>\nGone skinny dipping.",
    "<b>Lewd:</b>\nPlayed strip poker.",
    "<b>Lewd:</b>\nHad a one-night stand.",
    "<b>Lewd:</b>\nGotten busy in a public place.",
    "<b>Lewd:</b>\nBeen nude in public.",
    "<b>Lewd:</b>\nFlashed someone.",
    "<b>Lewd:</b>\nGotten busy in a car.",
    "<b>Lewd:</b>\nHad a friend with benefits.",
    "<b>Lewd:</b>\nSent nudes.",
    "<b>Lewd:</b>\nReceived nudes.",
    "<b>Lewd:</b>\nGotten a sex-related injury.",
    "<b>Lewd:</b>\nHad a wardrobe malfunction.",
    "<b>Lewd:</b>\nPaid for adult content.",
    "<b>Lewd:</b>\nJoined the mile-high club.",
    "<b>Lewd:</b>\nGone commando.",
    "<b>Lewd:</b>\nSexted an ex.",
    "<b>Lewd:</b>\nSent a sext to the wrong person.",
    "<b>Lewd:</b>\nWalked in on my parents bangin'.",
    "<b>Lewd:</b>\nFilmed an intimate moment.",
    "<b>Lewd:</b>\nBeen to a strip club.",
    "<b>Lewd:</b>\nGotten busy with a stripper, escort, hooker, etc.",
    "<b>Lewd:</b>\nHad phone sex.",
    "<b>Lewd:</b>\nBeen caught masturbating.",
    "<b>Lewd:</b>\nGone streaking.",
    "<b>Lewd:</b>\nCalled someone Mommy/Daddy and actually enjoyed it.",
    "<b>Lewd:</b>\nBought a lovense.",
    "<b>Lewd:</b>\nConsensually choked someone.",
    "<b>Lewd:</b>\nBeen submissive.",
    "<b>Lewd:</b>\nBeen dominant.",
    "<b>Lewd:</b>\nOwned Lingerie.",
    "<b>Lewd:</b>\nOwned a collar.",
    "<b>Lewd:</b>\nUsed a home appliance for pleasure.",
    "<b>Lewd:</b>\nBroken a toy.",
    "<b>Lewd:</b>\nBeen choked.",
    "<b>Lewd:</b>\nTried pole dancing.",
    "<b>Lewd:</b>\nBeen tied up.",
    "<b>Lewd:</b>\nBought Nsfw stuff online.",
    "<b>Lewd:</b>\nPosted NSFW content online.",
    "<b>Lewd:</b>\nEnjoyed being called princess~.",
    "<b>Lewd:</b>\nEnjoyed being called puppy~.",
    "<b>Lewd:</b>\nGave someone a \"Dance\".",
    "<b>Lewd:</b>\nBeen someone's Master or Owner.",
    "<b>Lewd:</b>\nBeen masochistic.",
    "<b>Lewd:</b>\nEnjoyed being degraded.",
    "<b>Lewd:</b>\nBeen a sadist.",
    "<b>Wholesome:</b>\nCried over a show.",
    "<b>Wholesome:</b>\nTold a lie to save someone from the truth.",
    "<b>Wholesome:</b>\nEnded up pissing myself from laughing.",
    "<b>Wholesome:</b>\nDone volunteer work.",
    "<b>Wholesome:</b>\nHad an imaginary friend.",
    "<b>Wholesome:</b>\nDonated blood or an organ.",
    "<b>Wholesome:</b>\nRescued an animal.",
    "<b>Wholesome:</b>\nHelped someone without ever expecting something in return.",
    "<b>Wholesome:</b>\nTaken a friend out and paid for them.",
    "<b>Wholesome:</b>\nGiven a gift that was worth over 500 dollars.",
    "<b>Wholesome:</b>\nBeen happy for a friend for succeeding at something.",
    "<b>Wholesome:</b>\nStood up for someone I did or did not know.",
    "<b>Wholesome:</b>\nBeen scared by something small.",
    "<b>Wholesome:</b>\nBeen told I am cute.",
    "<b>Wholesome:</b>\nBeen considered wholesome.",
    "<b>Wholesome:</b>\nOwned a stuffie.",
    "<b>Wholesome:</b>\nDonated to charity.",
    "<b>Wholesome:</b>\nBeen a good role-model.",
    "<b>Wholesome:</b>\nHad butterflies.",
    "<b>Wholesome:</b>\nMade someone breakfast.",
    "<b>Wholesome:</b>\nWanted the best for someone even if it wasn't necessarily me.",
    "<b>Wholesome:</b>\nWanted cuddles or a hug.",
    "<b>Wholesome:</b>\nWanted to pet an animal I saw walking.",
    "<b>Wholesome:</b>\nBeen shy.",
    "<b>Wholesome:</b>\nBeen Uncontrollably giggly.",
    "<b>Wholesome:</b>\nNOT felt loved by my family.",
    "<b>Wholesome:</b>\nBeen able to do an impression perfectly.",
    "<b>Wholesome:</b>\nCuddled my pet.",
    "<b>Wholesome:</b>\nBeen woken up by my pet.",
    "<b>Wholesome:</b>\nChanged my hair color.",
    "<b>Wholesome:</b>\nLooked at memes for over an hour.",
    "<b>Wholesome:</b>\nNot asked for an order change that was clearly wrong at a restaurant.",
    "<b>Wholesome:</b>\nTipped someone 100 dollars or more.",
    "<b>Wholesome:</b>\nBroken a bone.",
    "<b>Wholesome:</b>\nFarted in a locked environment with other people around.",
    "<b>Wholesome:</b>\nBeen a part of a prank day at school.",
    "<b>Wholesome:</b>\nLived in the same place for more than 5 years.",
    "<b>Wholesome:</b>\nGotten a tattoo.",
    "<b>Wholesome:</b>\nHad a cute voice.",
    "<b>Wholesome:</b>\nBeen in a play with a lead role.",
    "<b>Wholesome:</b>\nHad more than one pet.",
    "<b>Wholesome:</b>\nOwned a Nintendo 64, SNES, Sega Dreamcast or a PS1.",
    "<b>Wholesome:</b>\nNot cared about my appearance.",
    "<b>Wholesome:</b>\nWatched a cartoon that is over 50 years old.",
    "<b>Wholesome:</b>\nWatched fireworks.",
    "<b>Wholesome:</b>\nBeen part of a parade.",
    "<b>Wholesome:</b>\nWon a dare or bet that was for 50 dollars or more.",
    "<b>Wholesome:</b>\nAte a Ghost Pepper or South Carolina Reaper.",
    "<b>Wholesome:</b>\nGone to a beach.",
    "<b>Wholesome:</b>\nGone camping.",
    "<b>Wholesome:</b>\nGone to open a door and missed the handle or knob.",
    "<b>Wholesome:</b>\nBeen on the toilet for longer than an hour.",
    "<b>Wholesome:</b>\nHit my head on a ceiling fan.",
    "<b>Wholesome:</b>\nBeen the soul survivor of a dodgeball team and won.",
    "<b>Wholesome:</b>\nWoke someone up by snoring.",
    "<b>Wholesome:</b>\nWoke myself up by snoring.",
    "<b>Wholesome:</b>\nPlayed hide and seek in the woods.",
    "<b>Wholesome:</b>\nOwned an exotic pet.",
    "<b>Wholesome:</b>\nBeen mistaken for the opposite gender.",
    "<b>Wholesome:</b>\nBeen adopted.",
    "<b>Wholesome:</b>\nDug out a wedgie in public.",
    "<b>Wholesome:</b>\nSeen the northern lights.",
    "<b>Wholesome:</b>\nBeen able to roll my tongue.",
    "<b>Wholesome:</b>\nHad a friend who I considered more family than my actual family.",
    "<b>Wholesome:</b>\nDropped my phone in any water.",
    "<b>Wholesome:</b>\nBrake checked someone.",
    "<b>Wholesome:</b>\nPracticed any form of martial arts.",
    "<b>Wholesome:</b>\nBullied the bully.",
    "<b>Wholesome:</b>\nMessed with a bee, wasp and/or hornet nest.",
    "<b>Wholesome:</b>\nUnderstood something my parents did or said years later.",
    "<b>Wholesome:</b>\nMessed up a text due to auto correct.",
    "<b>Wholesome:</b>\nWished life was like an anime or a game.",
    "<b>Wholesome:</b>\nBombed a pickup line.",
    "<b>Wholesome:</b>\nLaughed at something I shouldn't have.",
    "<b>Wholesome:</b>\nDrawn on someone's face while they were asleep.",
    "<b>Wholesome:</b>\nMade a group of friends because of this map!",
    "<b>Wholesome:</b>\nFound love because of this map!",
    "<b>Wholesome:</b>\nBeen \"Rick Rolled\".",
    "<b>Wholesome:</b>\nHaven't won on this map.",
    "<b>Wholesome:</b>\nMade two toys \"kiss\" each other.",
    "<b>Wholesome:</b>\nHad a crush on a friend's sibling.",
    "<b>Wholesome:</b>\nHad a crush on a teacher.",
    "<b>Wholesome:</b>\nGotten heated during a family game night.",
    "<b>Wholesome:</b>\nEaten whipped cream straight out of the can.",
    "<b>Wholesome:</b>\nLaughed so hard I spit out my drink.",
    "<b>Wholesome:</b>\nUsed someone else's Netflix password.",
    "<b>Wholesome:</b>\nFallen asleep in class.",
    "<b>Wholesome:</b>\nSeen an alligator in real life.",
    "<b>Wholesome:</b>\nWon the lottery.",
    "<b>Wholesome:</b>\nClimbed out of a window.",
    "<b>Wholesome:</b>\nGot stopped by airport security.",
    "<b>Wholesome:</b>\nRan a marathon.",
    "<b>Wholesome:</b>\nMade a speech in front of 100 people or more.",
    "<b>Wholesome:</b>\nSpent more than $100 on a piece of clothing.",
    "<b>Wholesome:</b>\nStayed overnight in the hospital.",
    "<b>Wholesome:</b>\nNut checked someone.",
    "<b>Wholesome:</b>\nBeen influenced by a show or movie in a good way.",
    "<b>Wholesome:</b>\nWanted to live in a different time period.",
    "<b>Wholesome:</b>\nPeeked on my own presents; birthday, Christmas or otherwise.",
    "<b>Wholesome:</b>\nForgiven someone for something.",
    "<b>Wholesome:</b>\nFought with a friend over something stupid.",
    "<b>Wholesome:</b>\nBeen friendzoned and happy about it.",
    "<b>Wholesome:</b>\nBeen the friend who let another crash at their house.",
    "<b>Wholesome:</b>\nBeen the friend that helped someone get into better shape.",
    "<b>Wholesome:</b>\nLoved the smell of fresh gasoline.",
    "<b>Wholesome:</b>\nHad an allergic reaction to something that nearly killed me.",
    "<b>Wholesome:</b>\nSpent an entire day on YouTube.",
    "<b>Wholesome:</b>\nPlayed a game in black and white or CRT.",
    "<b>Wholesome:</b>\nHad hair that so long that it touched my butt.",
    "<b>Wholesome:</b>\nGone mudding.",
    "<b>Wholesome:</b>\nPicked, scratched or rubbed my nose until it bled.",
    "<b>Wholesome:</b>\nFound lice in my hair.",
    "<b>Wholesome:</b>\nHad bed bugs.",
    "<b>Wholesome:</b>\nChugged an entire 2L of any soda in one go.",
    "<b>Wholesome:</b>\nGiven myself a wedgie on a door or piece of furniture.",
    "<b>Wholesome:</b>\nHad a friend with a prosthetic limb or have one myself.",
    "<b>Wholesome:</b>\nWent ghost-hunting in abandoned houses.",
    "<b>Wholesome:</b>\nPlayed with a Ouija board in a cemetery.",
    "<b>Wholesome:</b>\nBeen a volunteer firefighter or first responder.",
    "<b>Wholesome:</b>\nActually kept my New Year's Resolution goal.",
    "<b>Wholesome:</b>\nSnuck snacks into a movie theater.",
    "<b>Wholesome:</b>\nWent dumpster diving.",
    "<b>Wholesome:</b>\nPicked up someone else's trash.",
    "<b>Wholesome:</b>\nPracticed any form of martial arts.",
    "<b>Wholesome:</b>\nUsed a coupon for a date.",
    "<b>Wholesome:</b>\nPut my finger into a pet’s mouth while yawning.",
    "<b>Wholesome:</b>\nLicked my fingers after eating food.",
    "<b>Wholesome:</b>\nCreated a fake account.",
    "<b>Wholesome:</b>\nRode in a shopping cart.",
    "<b>Wholesome:</b>\nTried to sleep with my eyes open.",
    "<b>Wholesome:</b>\nSpoke to my pets about the meaning of life.",
    "<b>Wholesome:</b>\nScreamed when I saw a spider, bug, or rodent.",
    "<b>Wholesome:</b>\nEaten dog or cat food.",
    "<b>Wholesome:</b>\nAdded Mentos to Coca-Cola.",
    "<b>Wholesome:</b>\nLooked at the stars through a telescope.",
    "<b>Wholesome:</b>\nSkipped hand washing after going to the toilet.",
    "<b>Wholesome:</b>\nFallen asleep in a movie theater.",
    "<b>Wholesome:</b>\nFallen asleep in the sun and got sunburnt.",
    "<b>Wholesome:</b>\nTold my friend’s joke but took the credit.",
    "<b>Wholesome:</b>\nPlayed pranks on someone on April 1st.",
    "<b>Wholesome:</b>\nBeen afraid of clowns.",
    "<b>Wholesome:</b>\nGoogled my full name to know the search results.",
    "<b>Wholesome:</b>\nForgotten the name of a person I just met.",
    "<b>Wholesome:</b>\nPracticed yoga or crossfit.",
    "<b>Wholesome:</b>\nChanged a baby’s diaper.",
    "<b>Wholesome:</b>\nSleepwalked.",
    "<b>Wholesome:</b>\nListened to the same song on repeat for more than a week.",
    "<b>Wholesome:</b>\nPretended to be busy to avoid meeting with someone.",
    "<b>Wholesome:</b>\nStood in the rain without an umbrella.",
    "<b>Wholesome:</b>\nThrown my phone at the wall.",
    "<b>Wholesome:</b>\nActually used a life hack.",
    "<b>Wholesome:</b>\nMade a snow angel.",
    "<b>Wholesome:</b>\nBeen afraid of the dark.",
    "<b>Wholesome:</b>\nGot a piercing.",
    "<b>Wholesome:</b>\nSlept without underwear.",
    "<b>Wholesome:</b>\nFallen in love with someone I met online.",
    "<b>Wholesome:</b>\nGifted somebody a hand-made Valentine’s Day card.",
    "<b>Wholesome:</b>\nBeen in a long distance relationship.",
    "<b>Wholesome:</b>\nTaken the first step to making peace after a fight.",
    "<b>Wholesome:</b>\nRemained blind to my partner’s faults.",
    "<b>Wholesome:</b>\nSpent the night at my significant other's house.",
    "<b>Wholesome:</b>\nForgiven a betrayal.",
    "<b>Wholesome:</b>\nPretended to be kind to people who I actually despised.",
    "<b>Wholesome:</b>\nLaughed at someone’s misfortune.",
    "<b>Wholesome:</b>\nLost faith in humanity.",
    "<b>Wholesome:</b>\nFelt guilty for hurting someone.",
    "<b>Wholesome:</b>\nWanted to change something in my past.",
    "<b>Wholesome:</b>\nStayed awake late into the night with someone on my mind.",
    "<b>Wholesome:</b>\nSat naked on leather.",
    "<b>Wholesome:</b>\nTaken a bathroom selfie.",
    "<b>Wholesome:</b>\nGiven my phone number to someone I just met.",
    "<b>Wholesome:</b>\nRan into a pole and/or wall.",
    "<b>Wholesome:</b>\nSlipped on ice.",
    "<b>Wholesome:</b>\nFailed to judge how deep a puddle was.",
    "<b>Wholesome:</b>\nUsed the wrong bathroom.",
    "<b>Wholesome:</b>\nPassed out after work.",
    "<b>Wholesome:</b>\nGotten into a flow state creating something.",
    "<b>Wholesome:</b>\nSuccessfully made a home cooked meal.",
    "<b>Wholesome:</b>\nAsked someone out on a date, face to face.",
    "<b>Wholesome:</b>\nJacked my sleep schedule way up.",
    "<b>Wholesome:</b>\nPainted a room in my house an entirely new color.",
    "<b>Wholesome:</b>\nMade it through an extremely hard time, only to look back and be amazed that I managed to do so.",
    "<b>Wholesome:</b>\nBeen genuinely scared by a thunderstorm.",
    "<b>Wholesome:</b>\nBroken a tool during a project of any kind.",
    "<b>Wholesome:</b>\nHad my school or computer project of any kind go corrupt on me.",
    "<b>Wholesome:</b>\nActually had my homework destroyed by a pet.",
    "<b>Wholesome:</b>\nPurposefully said the cringiest thing i could think of in a moment.",
    "<b>Wholesome:</b>\nBeen hella bad at building in Minecraft.",
    "<b>Wholesome:</b>\nFallen from at least a story worth of height.",
    "<b>Wholesome:</b>\nStopped playing a game with a certain friend cause they beat me in it every time.",
    "<b>Wholesome:</b>\nHave injured myself or another with a firework.",
    "<b>Wholesome:</b>\nBeen catfished.",
    "<b>Wholesome:</b>\nBeen patriotic for my own country.",
    "<b>Wholesome:</b>\nRegretted picking up an extra shift.",
    "<b>Wholesome:</b>\nBeen caught speeding.",
    "<b>Wholesome:</b>\nHad a sleepover.",
    "<b>Wholesome:</b>\nStubbed my toe.",
    "<b>Wholesome:</b>\nHit my funny bone.",
    "<b>Wholesome:</b>\nHad my foot fall asleep.",
    "<b>Wholesome:</b>\nBeen apart of Generation Z.",
    "<b>Wholesome:</b>\nSaved somebody that was in an accident.",
    "<b>Wholesome:</b>\nHelped a elder across the street.",
    "<b>Wholesome:</b>\nSeen one of the seven wonders ex Pyramids, Wall of China.",
    "<b>Wholesome:</b>\nHad your first kiss.",
    "<b>Wholesome:</b>\nSeen any of the Disney classics like Snow White, Lion King 1 etc.",
    "<b>Wholesome:</b>\nWanted to get married.",
    "<b>Wholesome:</b>\nWanted to make a family.",
    "<b>Wholesome:</b>\nHelped someone jump their car.",
    "<b>Wholesome:</b>\nPayed for a strangers food.",
    "<b>Wholesome:</b>\nGiven money to someone on the streets.",
    "<b>Wholesome:</b>\nDid something for free for someone that usually cost money.",
    "<b>Wholesome:</b>\nQuit an addiction.",
    "<b>Wholesome:</b>\nRemoved someone toxic out of my life.",
    "<b>Wholesome:</b>\nBeen proud of my own development.",
    "<b>Wholesome:</b>\nLiked how i looked in the mirror.",
    "<b>Wholesome:</b>\nMown the lawn.",
    "<b>Wholesome:</b>\nBought promise rings with my SO.",
    "<b>Wholesome:</b>\nLiked cats more than dogs.",
    "<b>Wholesome:</b>\nLiked dogs more than cats.",
    "<b>Wholesome:</b>\nBeen to a zoo/aquarium.",
    "<b>Wholesome:</b>\nHad a life-size stuffed animal.",
    "<b>Wholesome:</b>\nBeen part of a charity or volunteer organization.",
    "<b>Wholesome:</b>\nDecorated a college dorm room.",
    "<b>Wholesome:</b>\nPlayed Trading card games.",
    "<b>Wholesome:</b>\nTried to open a door the wrong way.",
    "<b>Wholesome:</b>\nNot understood a joke someone has told me.",
    "<b>Wholesome:</b>\nBeen Corrupted by someone.",
    "<b>Work:</b>\nBeen fired.",
    "<b>Work:</b>\nTried to blackmail someone at work.",
    "<b>Work:</b>\nCaught coworkers bangin'.",
    "<b>Work:</b>\nHad sex with my boss for a position or raise.",
    "<b>Work:</b>\nLied outright to a customer or client’s face.",
    "<b>Work:</b>\nTold the honest and brutal truth to a customer's face.",
    "<b>Work:</b>\nBeen robbed at a place I was working at.",
    "<b>Work:</b>\nStolen from where I've worked.",
    "<b>Work:</b>\nHad to fire someone.",
    "<b>Work:</b>\nHad a policy put in place that was so stupid or counterproductive I quit.",
    "<b>Work:</b>\nHad a bad boss.",
    "<b>Work:</b>\nRealized I need to work out because of my job.",
    "<b>Work:</b>\nWork more than 12 hours in a day.",
    "<b>Work:</b>\nWork more than 100 hours in a week.",
    "<b>Work:</b>\nJust wanted to watch the place I work at be burned to the ground.",
    "<b>Work:</b>\nWorked more than three jobs at a time.",
    "<b>Work:</b>\nGotten someone fired.",
    "<b>Work:</b>\nYelled at a customer or client.",
    "<b>Work:</b>\nFallen asleep while at work.",
    "<b>Work:</b>\nLeft without a two weeks' notice.",
    "<b>Work:</b>\nGone to work drunk or high or while at work, got drunk or high.",
    "<b>Work:</b>\nGot a bonus.",
    "<b>Work:</b>\nBeen in a Union or Guild.",
    "<b>Work:</b>\nBeen a freelancer or contractor.",
    "<b>Work:</b>\nMade over 250 dollars with a single art piece I made.",
    "<b>Work:</b>\nGotten into a fight while at work that became physical.",
    "<b>Work:</b>\nWorked retail, restaurants, bars, clubs, sales, or customer service.",
    "<b>Work:</b>\nBeen threatened by a customer or client.",
    "<b>Work:</b>\nWorked night or graveyard shift.",
    "<b>Work:</b>\nExperienced extremely dangerous conditions where I worked.",
    "<b>Work:</b>\nThought I could get my dream job.",
    "<b>Work:</b>\nTraveled for work.",
    "<b>Work:</b>\nBeen laid off or asked to resign.",
    "<b>Work:</b>\nBeen given Employee of the Month or an award for my work.",
    "<b>Work:</b>\nBroke something expensive at work.",
    "<b>Work:</b>\nBeen seriously injured at work.",
    "<b>Work:</b>\nBeen sued for something I said or did at work.",
    "<b>Work:</b>\nHeld a job for longer than 1 year.",
    "<b>Work:</b>\nHeld a job for less than a month.",
    "<b>Work:</b>\nLearned something so bad about a place I worked at, I would never eat or shop there again.",
    "<b>Work:</b>\nBeen a Supervisor or Manager.",
    "<b>Work:</b>\nBeen on the phone with a customer or client for longer than an hour.",
    "<b>Work:</b>\nWorked at a large event such as a convention, wedding, or otherwise.",
    "<b>Work:</b>\nHad someone bad-mouth me in a different language and then spoke to them in that language.",
    "<b>Work:</b>\nHad to file a police report over an incident that happened at work.",
    "<b>Work:</b>\nHad a job I actually was happy about.",
    "<b>Work:</b>\nBeen discriminated against where I work.",
    "<b>Work:</b>\nBeen demoted.",
    "<b>Work:</b>\nGot let go from a job just because someone didn't like me.",
    "<b>Work:</b>\nNOT worked a day in my life.",
    "<b>Work:</b>\nEaten someone else’s lunch from the office fridge.",
    "<b>Work:</b>\nFaked being sick to skip work.",
    "<b>Work:</b>\nSnitched on someone else at work.",
    "<b>Work:</b>\nLied on my resume.",
    "<b>Work:</b>\nLied about my income.",
    "<b>Work:</b>\nHad to clean up someone's period in the restroom.",
    "<b>Work:</b>\nHeld a job that was commission based only.",
    "<b>Work:</b>\nHad to deal with a customer who was incredibly dumb.",
    "<b>Work:</b>\nHad to explain how something actually works.",
    "<b>Work:</b>\nWorked with customer support.",
    "<b>Work:</b>\nSucked up to a bad boss/superior for a promotion.",
    "<b>Work:</b>\nGotten into the department you wanted.",
    "<b>Work:</b>\nStolen Office Supplies.",
    "<b>Work:</b>\nSkipped lunch because you had to much work or just simply forgot.",
    "<b>Work:</b>\nGotten a licence related to work for example a welding licence or a truck card.",
    "<b>Work:</b>\nWorked extra hours to buy something you really wanted.",
    "<b>Work:</b>\nYelled at your boss.",
    "<b>Work:</b>\nTook pride in something I did at work.",
    "<b>Work:</b>\nBeen relieved to have been fired or quit my job.",
    "<b>Work:</b>\nHad a panic attack because of my job.",
    "<b>Work:</b>\nNeeded security clearance for a place I worked at.",
    "<b>Work:</b>\nStarted my own company.",
    "<b>Work:</b>\nBeen salary.",
    "<b>Work:</b>\nBeen hourly.",
    "<b>Work:</b>\nWorked for the government at any level.",
    "<b>Work:</b>\nGotten a friend hired at my job!",
    "<b>Intoxicated:</b>\nBeen the blackout drunk who has done awful stuff.",
    "<b>Intoxicated:</b>\nBeen the emotional drunk who can't stop crying.",
    "<b>Intoxicated:</b>\nBeen the drunken philosopher.",
    "<b>Intoxicated:</b>\nHad a trip so bad it haunts me to this day.",
    "<b>Intoxicated:</b>\nTripped out so hard I lost my mind.",
    "<b>Intoxicated:</b>\nBeen so high the paranoia set in.",
    "<b>Intoxicated:</b>\nBeen so intoxicated I thought my heart or lungs were about to fail.",
    "<b>Intoxicated:</b>\nBeen cross faded into a new dimension.",
    "<b>Intoxicated:</b>\nHad a trip so eye-opening I believed I had the answers.",
    "<b>Intoxicated:</b>\nTripped so bad it genuinely changed my life.",
    "<b>Intoxicated:</b>\nSober up in a nano second because something just got too damn real.",
    "<b>Intoxicated:</b>\nHad the cops called on a party I was at while intoxicated.",
    "<b>Intoxicated:</b>\nBeen high for an entire 24 hours.",
    "<b>Intoxicated:</b>\nBeen high for an entire week without sobering up at all.",
    "<b>Intoxicated:</b>\nEaten way too much of an edible.",
    "<b>Intoxicated:</b>\nDowned a whole rack of edibles without the knowledge they were.",
    "<b>Intoxicated:</b>\nRaged out and lost my mind while high.",
    "<b>Intoxicated:</b>\nDone more than two types of drugs inside of 24 hours.",
    "<b>Intoxicated:</b>\nBeen seriously injured while intoxicated.",
    "<b>Intoxicated:</b>\nSetup a camera system to find out what I do while drunk or high.",
    "<b>Intoxicated:</b>\nHad to keep myself awake because I was too high or drunk.",
    "<b>Intoxicated:</b>\nBeen high/drunk to the point of spinning.",
    "<b>Intoxicated:</b>\nBeen the affectionate one while intoxicated.",
    "<b>Intoxicated:</b>\nBeen the functioning type while intoxicated.",
    "<b>Intoxicated:</b>\nVomited in someone's mouth while intoxicated.",
    "<b>Intoxicated:</b>\nStolen something from a house party while intoxicated.",
    "<b>Intoxicated:</b>\nPeed on a building or car that was not mine while intoxicated.",
    "<b>Intoxicated:</b>\nSeen someone who was way past the line do something insane.",
    "<b>Intoxicated:</b>\nTried to stand up only to face plant into the ground.",
    "<b>Intoxicated:</b>\nTalked to an inanimate object.",
    "<b>Intoxicated:</b>\nHurt yourself while intoxicated while trying to impress someone.",
    "<b>Intoxicated:</b>\nPlayed Beer Pong!",
    "<b>Intoxicated:</b>\nBeen the handsy drunk.",
    "<b>Intoxicated:</b>\nBlacked out drunk and had no clue where I was.",
    "<b>Intoxicated:</b>\nBeen the drunk driver.",
    "<b>Intoxicated:</b>\nBeen intoxicated below the legal age in your country.",
    "<b>Intoxicated:</b>\nHave a extremely high alcohol tolerance.",
    "<b>School:</b>\nCheated on a test and passed.",
    "<b>School:</b>\nServed detention.",
    "<b>School:</b>\nGot suspended.",
    "<b>School:</b>\nGot kicked out of a school.",
    "<b>School:</b>\nFailed a grade or course.",
    "<b>School:</b>\nBeen held back a grade.",
    "<b>School:</b>\nSkipped a grade.",
    "<b>School:</b>\nGot into a fight at school.",
    "<b>School:</b>\nBrought a weapon to school.",
    "<b>School:</b>\nBrought drugs, booze, tobacco or nicotine products to school.",
    "<b>School:</b>\nUsed an unconventional item as a weapon (book, desk, etc.).",
    "<b>School:</b>\nHad problems with attendance.",
    "<b>School:</b>\nPlayed in band or orchestra.",
    "<b>School:</b>\nBeen part of the yearbook team.",
    "<b>School:</b>\nGone to private school.",
    "<b>School:</b>\nBeen horribly humiliated at school.",
    "<b>School:</b>\nBeen home schooled.",
    "<b>School:</b>\nBeen in AP classes.",
    "<b>School:</b>\nBeen on the honor roll or dean's list.",
    "<b>School:</b>\nBeen in a food fight.",
    "<b>School:</b>\nSkipped class or classes.",
    "<b>School:</b>\nNOT gone to a dance.",
    "<b>School:</b>\nAttended Prom.",
    "<b>School:</b>\nUsed what I learned in school.",
    "<b>School:</b>\nGot a Diploma or GED.",
    "<b>School:</b>\nBeen the one to command a project.",
    "<b>School:</b>\nWon multiple sports games in a row.",
    "<b>School:</b>\nGone to National's in a sports team.",
    "<b>School:</b>\nGone to National's and won in a sports team.",
    "<b>School:</b>\nTraveled out of state to an event with a band or orchestra.",
    "<b>School:</b>\nGone to boarding school.",
    "<b>School:</b>\nGone to a year round school.",
    "<b>School:</b>\nLearned one or more languages at school.",
    "<b>School:</b>\nTook an art class.",
    "<b>School:</b>\nTook an automotive class.",
    "<b>School:</b>\nTook a Shop class.",
    "<b>School:</b>\nTook a Home Ec class.",
    "<b>School:</b>\nTook a Veterinarian class.",
    "<b>School:</b>\nTook a Criminal Justice class.",
    "<b>School:</b>\nTook a Law class.",
    "<b>School:</b>\nTook a Business class.",
    "<b>School:</b>\nPlayed hooky.",
    "<b>School:</b>\nHad a snow day and school was cancelled.",
    "<b>School:</b>\nGot a grant or scholarship.",
    "<b>School:</b>\nHad a job while attending school.",
    "<b>School:</b>\nWalked more than a mile to school.",
    "<b>School:</b>\nBeen pantsed in front of people at school.",
    "<b>School:</b>\nRead a book for English class and actually enjoyed it.",
    "<b>School:</b>\nBeen on a field trip to a park.",
    "<b>School:</b>\nBeen on a field trip to a movie.",
    "<b>School:</b>\nTook advantage of a substitute teacher's lack of knowledge of school policy.",
    "<b>School:</b>\nGenuinely enjoyed a teacher's way of teaching.",
    "<b>School:</b>\nCramed overnight for a test.",
    "<b>School:</b>\nWoken up before 7am just to get ready for school.",
    "<b>School:</b>\nDespised a teacher.",
    "<b>School:</b>\nGot the highest grade in your class on a test.",
    "<b>School:</b>\nBeen the teachers pet.",
    "<b>School:</b>\nNailed a test you did not study for at all.",
    "<b>School:</b>\nGotten yelled at for skipping too many classes.",
    "<b>School:</b>\nBeen the school bully.",
    "<b>School:</b>\nGot a teacher fired.",
    "<b>School:</b>\nYelled at a teacher.",
    "<b>School:</b>\nHad to clean something as a form of punishment at school.",
    "<b>School:</b>\nDid community service through my school.",
    "<b>School:</b>\nHad a 4.0 gpa at any point in my school career.",
    "<b>School:</b>\nGone to a competition for a club.",
    "<b>School:</b>\nBeen invited to a highly rated school.",
    "<b>School:</b>\nTaken a religion class.",
    "<b>School:</b>\nBeen out of state or country for a field trip.",
    "<b>School:</b>\nHad mandatory foreign language classes.",
    "<b>School:</b>\nWrote a paper last second.",
    "<b>School:</b>\nTaken a course because you genuinely like the topic.",
    "<b>School:</b>\nBeen the quiet kid at the school.",
    "<b>School:</b>\nTaken classes on unusual topics.",
    "<b>Relationships:</b>\nBeen the side piece.",
    "<b>Relationships:</b>\nHad a secret that could never be revealed because of how bad it is.",
    "<b>Relationships:</b>\nBeen disowned by family and or friends for a choice I made.",
    "<b>Relationships:</b>\nFelt like a burden.",
    "<b>Relationships:</b>\nRoleplayed.",
    "<b>Relationships:</b>\nBeen engaged or married.",
    "<b>Relationships:</b>\nMet someone in a game of any variety and then in real life.",
    "<b>Relationships:</b>\nBroke up with someone over the phone.",
    "<b>Relationships:</b>\nCheated.",
    "<b>Relationships:</b>\nBeen with someone because of their money.",
    "<b>Relationships:</b>\nStayed with someone just because of the sex.",
    "<b>Relationships:</b>\nCalled someone the wrong name.",
    "<b>Relationships:</b>\nHad a friend with benefits.",
    "<b>Relationships:</b>\nFell out of love with someone.",
    "<b>Relationships:</b>\nBelieved in love at first sight.",
    "<b>Relationships:</b>\nStood someone up.",
    "<b>Relationships:</b>\nBroken up with someone because of something they do or began doing.",
    "<b>Relationships:</b>\nBeen with someone for more than a year.",
    "<b>Relationships:</b>\nBeen in a stable relationship.",
    "<b>Relationships:</b>\nGone back to a bad ex.",
    "<b>Relationships:</b>\nBeen told I was a great listener.",
    "<b>Relationships:</b>\nFelt used in relationship.",
    "<b>Relationships:</b>\nHad a kiss that was pure electricity.",
    "<b>Relationships:</b>\nBeen with someone shorter than me.",
    "<b>Relationships:</b>\nBeen with someone taller than me.",
    "<b>Relationships:</b>\nBeen the toxic one in the relationship.",
    "<b>Relationships:</b>\nStole from my significant other.",
    "<b>Relationships:</b>\nBeen on blind date that worked out.",
    "<b>Relationships:</b>\nHad to give up on someone I loved because they were no longer stable.",
    "<b>Relationships:</b>\nBet against my significant other.",
    "<b>Relationships:</b>\nLied about my interests in something just to date someone.",
    "<b>Relationships:</b>\nTricked my significant other with a pregnancy scare.",
    "<b>Relationships:</b>\nBelieved I could tell my significant other literally everything without fear.",
    "<b>Relationships:</b>\nHad to lie about how much a hobby costs.",
    "<b>Relationships:</b>\nBeen with more than one person at the same time.",
    "<b>Relationships:</b>\nTold someone I loved them within the first month of dating them.",
    "<b>Relationships:</b>\nSettled for someone.",
    "<b>Relationships:</b>\nMet someone in a club or bar that I ended up dating.",
    "<b>Relationships:</b>\nMet someone where I worked that I ended up dating.",
    "<b>Relationships:</b>\nTold someone I would die for them and meant it.",
    "<b>Relationships:</b>\nTried to make a relationship work.",
    "<b>Relationships:</b>\nBeen genuinely happy for another’s relationship.",
    "<b>Relationships:</b>\nPlayed with someone's heart.",
    "<b>Relationships:</b>\nFelt forced to stay with someone due to their instability.",
    "<b>Relationships:</b>\nDone something special for my significant other that made them cry.",
    "<b>Relationships:</b>\nHad my heart broken or broke someone's heart.",
    "<b>Relationships:</b>\nGot out of the friend zone and dated the person who friend zoned me or I friend zoned .",
    "<b>Relationships:</b>\nLoved the way my significant other dresses.",
    "<b>Relationships:</b>\nPlayed off something my significant other said that actually hurt.",
    "<b>Relationships:</b>\nHad a sugar daddy/mommy.",
    "<b>Relationships:</b>\nSpoken up at wedding and got it cancelled.",
    "<b>Relationships:</b>\nHumiliated an ex.",
    "<b>Relationships:</b>\nCheated on someone through a video game.",
    "<b>Relationships:</b>\nKicked someone out of my life which resulted in them being homeless.",
    "<b>Relationships:</b>\nStarted a relationship through a game.",
    "<b>Relationships:</b>\nBeen in a long distance relationship that worked.",
    "<b>Relationships:</b>\nHad a BFF you're still friends with to this day.",
    "<b>Relationships:</b>\nHad a one night stand turn into a relationship.",
    "<b>Relationships:</b>\nBroken up with somebody that was only meant to be a fling.",
    "<b>Relationships:</b>\nBroken up with each other because of a video game.",
    "<b>Relationships:</b>\nCut someone out of my life cause they rejected me romantically.",
    "<b>Relationships:</b>\nSimped.",
    "<b>Relationships:</b>\nHad a relationship that lasted less than a week.",
    "<b>Relationships:</b>\nBeen on a dating platform.",
    "<b>Relationships:</b>\nBeen in a relationship with someone who is in an emergency service. Such as a cop or in an ambulance.",
    "<b>Relationships:</b>\nHad a crush on someone in this room.",
    "<b>Relationships:</b>\nBroke someone's trust.",
    "<b>Relationships:</b>\nGone back and forth on rather I should be with someone or not.",
    "<b>Relationships:</b>\nBeen Ghosted.",
    "<b>Relationships:</b>\nGhosted.",
    "<b>Relationships:</b>\nThought I had found the one.",
    "<b>Relationships:</b>\nTook a long time to recover from a relationship ending.",
    "<b>Relationships:</b>\nHyper focused on something to get over someone.",
    "<b>Relationships:</b>\nLost a relationship to someone due to an addiction.",
    "<b>Relationships:</b>\nHad a crazy break up.",
    "<b>Relationships:</b>\nThought I am never getting married.",
    "<b>Relationships:</b>\nMet someone at a convention/event and ended up dating them.",
    "<b>Relationships:</b>\nFriendzoned someone.",
    "<b>Relationships:</b>\nNever started dating (move up if you have never dated someone).",
    "<b>Relationships:</b>\nBeen too popular with the opposite gender.",
    "<b>Illegal:</b>\nBeen jail baited.",
    "<b>Illegal:</b>\nRobbed someone.",
    "<b>Illegal:</b>\nScammed someone for more than 1,000 dollars.",
    "<b>Illegal:</b>\nBought or sold drugs at a weight of 1 pound or more.",
    "<b>Illegal:</b>\nBeen a part of or associated with a gang.",
    "<b>Illegal:</b>\nTaken or given a bribe.",
    "<b>Illegal:</b>\nPirated any form of media or art.",
    "<b>Illegal:</b>\nDone anything on the dark web.",
    "<b>Illegal:</b>\nDone graffiti.",
    "<b>Illegal:</b>\nStolen credit card information.",
    "<b>Illegal:</b>\nStolen someone’s identity.",
    "<b>Illegal:</b>\nImpersonated someone.",
    "<b>Illegal:</b>\nTrespassed.",
    "<b>Illegal:</b>\nStolen a vehicle.",
    "<b>Illegal:</b>\nCommitted fraud.",
    "<b>Illegal:</b>\nFalsely accused someone of something.",
    "<b>Illegal:</b>\nMade or used a malicious program.",
    "<b>Illegal:</b>\nBeen on parole or probation.",
    "<b>Illegal:</b>\nOwned and used illegal fireworks.",
    "<b>Illegal:</b>\nBeen a part of any form of malpractice.",
    "<b>Illegal:</b>\nLied to my probation or parole officer.",
    "<b>Illegal:</b>\nSwapped my urine sample out for someone else's.",
    "<b>Illegal:</b>\nGrown or made drugs in my home or yard.",
    "<b>Illegal:</b>\nCharged with indecent exposure.",
    "<b>Illegal:</b>\nCommitted arson.",
    "<b>Illegal:</b>\nStolen cable service.",
    "<b>Illegal:</b>\nBeen publicly intoxicated.",
    "<b>Illegal:</b>\nDestroyed someone's house at a party.",
    "<b>Illegal:</b>\nBeen a peeping tom.",
    "<b>Illegal:</b>\nJay-walked.",
    "<b>Illegal:</b>\nHacked somebody's account.",
    "<b>Illegal:</b>\nPickpocketed.",
    "<b>Illegal:</b>\nBeen pulled over by a cop.",
    "<b>Illegal:</b>\nGotten somebody in jail for something you did.",
    "<b>Illegal:</b>\nBeen in a prison gang.",
    "<b>Illegal:</b>\nResisted Getting Arrested.",
    "<b>Illegal:</b>\nGone significantly over the speed limit.",
    "<b>Illegal:</b>\nShoplifted.",
    "<b>Illegal:</b>\nCommitted Break and Enter.",
    "<b>Illegal:</b>\nDrove without a license.",
    "<b>Illegal:</b>\nSmuggled something.",
    "<b>Illegal:</b>\nCommitted a crime worth a year or more of prison time.",
    "<b>Illegal:</b>\nDriven/been in a vehicle driving the wrong way down a one-way street.",
    "<b>Illegal:</b>\nRemotely or directly tampered with a public WiFi network.",
    "<b>Illegal:</b>\nBeen freight hopping.",
    "<b>Illegal:</b>\nDriven any road vehicle without an appropriate license/endorsement.",
    "<b>Illegal:</b>\nUnlawfully climbed a building or structure.",
    "<b>Illegal:</b>\nCommitted a crime without realizing it until later.",
    "<b>Illegal:</b>\nBeen involved in a major scandal.",
    "<b>Personal:</b>\nGone to college or university and finished.",
    "<b>Personal:</b>\nHit a parked vehicle.",
    "<b>Personal:</b>\nBeen robbed.",
    "<b>Personal:</b>\nBelieved in a religion.",
    "<b>Personal:</b>\nThought my political views would change.",
    "<b>Personal:</b>\nLeft my home country.",
    "<b>Personal:</b>\nBeen to juvie, jail, rehab or a mental ward.",
    "<b>Personal:</b>\nFlirted my way out of a ticket.",
    "<b>Personal:</b>\nEavesdropped on something and ended up scarred for life.",
    "<b>Personal:</b>\nBeen the designated driver.",
    "<b>Personal:</b>\nBelieved in a code of conduct.",
    "<b>Personal:</b>\nHumiliated someone.",
    "<b>Personal:</b>\nDone something that got my friend in trouble.",
    "<b>Personal:</b>\nPooped myself.",
    "<b>Personal:</b>\nGone skinny dipping.",
    "<b>Personal:</b>\nDriven a car naked or topless.",
    "<b>Personal:</b>\nFlashed someone.",
    "<b>Personal:</b>\nGot into a random fight.",
    "<b>Personal:</b>\nBeen to a concert.",
    "<b>Personal:</b>\nClogged a toilet in a public restroom.",
    "<b>Personal:</b>\nDrank before I turned 21.",
    "<b>Personal:</b>\nCaught something on fire while trying to cook.",
    "<b>Personal:</b>\nPretended to know someone I did not know.",
    "<b>Personal:</b>\nBeen a wing man successfully.",
    "<b>Personal:</b>\nTalked trash behind someone's back.",
    "<b>Personal:</b>\nBeen evicted.",
    "<b>Personal:</b>\nTried to be trendy.",
    "<b>Personal:</b>\nConsidered or got plastic surgery.",
    "<b>Personal:</b>\nBeen arrested, fined, or convicted of something.",
    "<b>Personal:</b>\nSnuck into a building or event.",
    "<b>Personal:</b>\nBeen kicked off a team.",
    "<b>Personal:</b>\nUsed a game’s stats and or rare items to flirt with someone.",
    "<b>Personal:</b>\nFelt out of touch with pop culture.",
    "<b>Personal:</b>\nGiven someone a sex hotline number to avoid them calling me.",
    "<b>Personal:</b>\nSubscribed to someone's Patreon.",
    "<b>Personal:</b>\nLed someone on.",
    "<b>Personal:</b>\nOwned a body pillow.",
    "<b>Personal:</b>\nExperienced something paranormal.",
    "<b>Personal:</b>\nExperienced my worst fear.",
    "<b>Personal:</b>\nBeen caught talking about someone and that person was behind me.",
    "<b>Personal:</b>\nHeld a grudge for a year or longer.",
    "<b>Personal:</b>\nUsed someone for my own personal gain.",
    "<b>Personal:</b>\nBackhanded someone to shut them up.",
    "<b>Personal:</b>\nBeen with a family member or friend's ex.",
    "<b>Personal:</b>\nFlirted with someone and knew they were taken.",
    "<b>Personal:</b>\nCalled or texted a friend to hangout after midnight.",
    "<b>Personal:</b>\nHad to help a drunk friend get into bed.",
    "<b>Personal:</b>\nBeen caught dancing naked.",
    "<b>Personal:</b>\nWalked into or through a glass door.",
    "<b>Personal:</b>\nWitnessed a crime and did nothing about it.",
    "<b>Personal:</b>\nJumped in a pool with all my clothes on.",
    "<b>Personal:</b>\nStayed out past three in the morning.",
    "<b>Personal:</b>\nLived completely alone.",
    "<b>Personal:</b>\nWatched TV for the entire day.",
    "<b>Personal:</b>\nWorked out.",
    "<b>Personal:</b>\nWent viral online.",
    "<b>Personal:</b>\nDone jury duty.",
    "<b>Personal:</b>\nSaved someone's life.",
    "<b>Personal:</b>\nFollowed a recipe from the internet.",
    "<b>Personal:</b>\nRegretted an apology.",
    "<b>Personal:</b>\nTold a lie to my best friend.",
    "<b>Personal:</b>\nLied about my age.",
    "<b>Personal:</b>\nMade up a story to impress someone.",
    "<b>Personal:</b>\nRepaired a car.",
    "<b>Personal:</b>\nLied to my parents about where I was going.",
    "<b>Personal:</b>\nBought my sibling something I wasn't supposed to.",
    "<b>Personal:</b>\nStolen money from a family member.",
    "<b>Personal:</b>\nPeed in the woods.",
    "<b>Personal:</b>\nBinged an entire Netflix series in one day.",
    "<b>Personal:</b>\nStolen clothes from a sibling.",
    "<b>Personal:</b>\nWore dirty underwear.",
    "<b>Personal:</b>\nHad someone at my parent's house without them knowing.",
    "<b>Personal:</b>\nBeen to a Disney park.",
    "<b>Personal:</b>\nHad a crush on a friend's partner.",
    "<b>Personal:</b>\nBeen on a cruise ship.",
    "<b>Personal:</b>\nBeen bungee jumping.",
    "<b>Personal:</b>\nPeed myself.",
    "<b>Personal:</b>\nOwned a disabled pet.",
    "<b>Personal:</b>\nAdopted an animal.",
    "<b>Personal:</b>\nChoked on my own spit.",
    "<b>Personal:</b>\nEaten an entire apple.",
    "<b>Personal:</b>\nBeen good at maths in my brain.",
    "<b>Personal:</b>\nGone on a theme park ride that actually scared me.",
    "<b>Personal:</b>\nGone for a walk that lasted more than three hours.",
    "<b>Personal:</b>\nWent in for an x-ray for any reason.",
    "<b>Personal:</b>\nFavorited this map.",
    "<b>Personal:</b>\nJoined this map's discord.",
    "<b>Personal:</b>\nFollowed Twisty10000 on twitter.",
    "<b>Personal:</b>\nBeen warned on this map.",
    "<b>Personal:</b>\nBeen kicked on this map.",
    "<b>Personal:</b>\nBeen vote kicked for winning too many times.",
    "<b>Personal:</b>\nPlayed at least 5 rounds of NHIE:A with the map creator.",
    "<b>Personal:</b>\nTried to run all the way to the end to end the game.",
    "<b>Personal:</b>\nBeen concerned for some of y'all.",
    "<b>Personal:</b>\nGotten sick and tired of being asked to favorite the map.",
    "<b>Personal:</b>\nPeed in a pool.",
    "<b>Personal:</b>\nDrunk-dialed my ex.",
    "<b>Personal:</b>\nRead a partner’s text messages.",
    "<b>Personal:</b>\nBeen hospitalized for something other than giving birth or being born.",
    "<b>Personal:</b>\nGone snowboarding / skiing.",
    "<b>Personal:</b>\nSent a stranger a drink.",
    "<b>Personal:</b>\nAccepted a drink from a stranger.",
    "<b>Personal:</b>\nDated or hooked up with someone 10 years or older.",
    "<b>Personal:</b>\nTexted or taken a call at the movies.",
    "<b>Personal:</b>\nConvinced a friend to leave a partner.",
    "<b>Personal:</b>\nConvinced a partner to leave a friend.",
    "<b>Personal:</b>\nBeen someone else’s alibi.",
    "<b>Personal:</b>\nHopped a turnstile.",
    "<b>Personal:</b>\nDonated an organ.",
    "<b>Personal:</b>\nLied to a law enforcement officer.",
    "<b>Personal:</b>\nBeen a maid of honor/best man.",
    "<b>Personal:</b>\nCalled a partner the wrong name.",
    "<b>Personal:</b>\nThought a friend’s baby was ugly.",
    "<b>Personal:</b>\nGone vegan.",
    "<b>Personal:</b>\nUsed a fake ID.",
    "<b>Personal:</b>\nHad chicken pox.",
    "<b>Personal:</b>\nHad a road rage incident.",
    "<b>Personal:</b>\nCut in line on purpose.",
    "<b>Personal:</b>\nShared someone else's secret.",
    "<b>Personal:</b>\nRuined someone else’s vacation.",
    "<b>Personal:</b>\nChipped a tooth.",
    "<b>Personal:</b>\nTried a fad diet.",
    "<b>Personal:</b>\nCut my own hair.",
    "<b>Personal:</b>\nAccidentally said “I love you” to someone.",
    "<b>Personal:</b>\nSnooped through a friend’s room, cabinets or property.",
    "<b>Personal:</b>\nWorked with someone I couldn’t stand.",
    "<b>Personal:</b>\nEaten food that broke the five-second rule.",
    "<b>Personal:</b>\nBlamed a fart on a pet.",
    "<b>Personal:</b>\nThought a cartoon character was hot.",
    "<b>Personal:</b>\nGoogled someone before a date.",
    "<b>Personal:</b>\nRe-gifted something.",
    "<b>Personal:</b>\nCrashed a party or wedding.",
    "<b>Personal:</b>\nGotten or given a hickey.",
    "<b>Personal:</b>\nTried moonshine.",
    "<b>Personal:</b>\nBeen in a talent show.",
    "<b>Personal:</b>\nTried to make an ex jealous.",
    "<b>Personal:</b>\nDriven a stick shift.",
    "<b>Personal:</b>\nDone a \"drive-by\" of an ex or crush’s house.",
    "<b>Personal:</b>\nBeen on TV.",
    "<b>Personal:</b>\nGotten sick on a date.",
    "<b>Personal:</b>\nHad food poisoning.",
    "<b>Personal:</b>\nPurposely given someone bad advice.",
    "<b>Personal:</b>\nHeckled a live performance.",
    "<b>Personal:</b>\nHad surgery.",
    "<b>Personal:</b>\nThrown someone else a surprise party.",
    "<b>Personal:</b>\nHad a surprise party thrown for me.",
    "<b>Personal:</b>\nBeen dumpster diving.",
    "<b>Personal:</b>\nBroken a bone.",
    "<b>Personal:</b>\nSlid into a stranger’s DMs.",
    "<b>Personal:</b>\nBeen in a helicopter.",
    "<b>Personal:</b>\nFlirted with a married person.",
    "<b>Personal:</b>\nSecond-guessed a relationship.",
    "<b>Personal:</b>\nHad braces.",
    "<b>Personal:</b>\nLied about my relationship status.",
    "<b>Personal:</b>\nLied on a dating profile.",
    "<b>Personal:</b>\nFallen in love.",
    "<b>Personal:</b>\nHad love at first sight.",
    "<b>Personal:</b>\nWished I had kids.",
    "<b>Personal:</b>\nSeen something creepy or wild while using public transportation.",
    "<b>Personal:</b>\nEaten an entire pizza alone.",
    "<b>Personal:</b>\nDrank an entire bottle of wine.",
    "<b>Personal:</b>\nRode a horse.",
    "<b>Personal:</b>\nFainted.",
    "<b>Personal:</b>\nBeen camping.",
    "<b>Personal:</b>\nSnuck into a movie.",
    "<b>Personal:</b>\nFired a gun.",
    "<b>Personal:</b>\nDropped a baby.",
    "<b>Personal:</b>\nShared a news story without reading past the headline.",
    "<b>Personal:</b>\nRan a red light.",
    "<b>Personal:</b>\nCried myself to sleep.",
    "<b>Personal:</b>\nBeen the subject of a rumor that wasn't true.",
    "<b>Personal:</b>\nSpread a rumor I knew wasn't true.",
    "<b>Personal:</b>\nMet a celebrity.",
    "<b>Personal:</b>\nCried at a party.",
    "<b>Personal:</b>\nLost my voice.",
    "<b>Personal:</b>\nBeen friends with twisty for longer than a year.",
    "<b>Personal:</b>\nCorrupted someone who was innocent.",
    "<b>Personal:</b>\nSpat in someone's food as a waiter/cook.",
    "<b>Personal:</b>\nMade promises I know I could not keep.",
    "<b>Personal:</b>\nLied to a significant other to keep a relationship.",
    "<b>Personal:</b>\nGiven someone an ultimatum.",
    "<b>Personal:</b>\nFound the real reason for why I drink or get high.",
    "<b>Personal:</b>\nHad to be told the way I acted in a relationship was abusive or abnormal.",
    "<b>Personal:</b>\nMissed a friend so much I cried over a random thought of them.",
    "<b>Personal:</b>\nBeen the friend to help my friend out of their rut.",
    "<b>Personal:</b>\nBeen the shoulder to cry on.",
    "<b>Personal:</b>\nWore the mask so well, people think I'm fine.",
    "<b>Personal:</b>\nBeen rejected by a crush.",
    "<b>Personal:</b>\nHad a diary or journal.",
    "<b>Personal:</b>\nHad a friend I actually believed in.",
    "<b>Personal:</b>\nBeen open with someone about my life only to watch it backfire.",
    "<b>Personal:</b>\nSaw a shadowy figure/entity.",
    "<b>Personal:</b>\nSuffered from Depression.",
    "<b>Personal:</b>\nSuffered from Social Anxiety.",
    "<b>Personal:</b>\nHad someone close die.",
    "<b>Personal:</b>\nWon a 1st place prize in something.",
    "<b>Personal:</b>\nAchieved a personal goal in life.",
    "<b>Personal:</b>\nWent ghost hunting .",
    "<b>Personal:</b>\nPulled an all-nighter working on homework.",
    "<b>Personal:</b>\nSaw something moving when it really wasn't.",
    "<b>Personal:</b>\nLied to someone to get out of a bad situation.",
    "<b>Personal:</b>\nDrank alcohol while being underaged.",
    "<b>Personal:</b>\nHad the urge to dropkick a child.",
    "<b>Personal:</b>\nHad my ex text me repeatedly to get back together.",
    "<b>Personal:</b>\nMade an OnlyFans.",
    "<b>Personal:</b>\nHit someone with a car.",
    "<b>Personal:</b>\nBeen pale.",
    "<b>Personal:</b>\nGiven birth.",
    "<b>Personal:</b>\nBeen under 6ft.",
    "<b>Personal:</b>\nSmoked weed.",
    "<b>Personal:</b>\nCosplayed.",
    "<b>Personal:</b>\nOwned a maid outfit.",
    "<b>Personal:</b>\nWished for different parents.",
    "<b>Personal:</b>\nBeen to Tokyo.",
    "<b>Personal:</b>\nPlayed akinator.",
    "<b>Personal:</b>\nLearned a second language fluently.",
    "<b>Personal:</b>\nBeen tired of being called short.",
    "<b>Personal:</b>\nBeen tired of being asked \"how's the weather up there?\".",
    "<b>Personal:</b>\nBeen so happy to be home after a long trip.",
    "<b>Personal:</b>\nFelt extremely alone in the world.",
    "<b>Personal:</b>\nBeen rejected by a crush and still cringe at how it went.",
    "<b>Personal:</b>\nBeen petty and regretted it.",
    "<b>Personal:</b>\nBeen petty.",
    "<b>Personal:</b>\nGotten into a car accident.",
    "<b>Personal:</b>\nBeen apart of a tech crew that ran sound or video for an event.",
    "<b>Personal:</b>\nPlayed hide and seek.",
    "<b>Personal:</b>\nHeard a song on the radio that you hated so many times, that you began to like it.",
    "<b>Personal:</b>\nFell in front of people.",
    "<b>Personal:</b>\nFell on top of someone.",
    "<b>Personal:</b>\nRan into a wall in the dark.",
    "<b>Personal:</b>\nRan from one side of the school to the other side about to miss class.",
    "<b>Personal:</b>\nDecorated your cap for graduation.",
    "<b>Personal:</b>\nHad my phone going off during a test.",
    "<b>Personal:</b>\nPoured milk before cereal.",
    "<b>Personal:</b>\nRidden A Camel.",
    "<b>Personal:</b>\nBeen involved in school drama.",
    "<b>Personal:</b>\nGave a secret valentine to a crush.",
    "<b>Personal:</b>\nTripped over nothing.",
    "<b>Personal:</b>\nBeen on tv.",
    "<b>Personal:</b>\nBeen expelled.",
    "<b>Personal:</b>\nBeen dress coded.",
    "<b>Personal:</b>\nPlayed hide and seek in the dark.",
    "<b>Personal:</b>\nHeld my phone above me in bed and accidentally let it slip out of your hand and hit your face.",
    "<b>Personal:</b>\nDropped my phone in the toilet.",
    "<b>Personal:</b>\nHad a night terror.",
    "<b>Personal:</b>\nLived in the middle of nowhere.",
    "<b>Personal:</b>\nScared the crap out of someone.",
    "<b>Personal:</b>\nBeen simped on because of my voice/accent.",
    "<b>Personal:</b>\nHad sleep paralysis.",
    "<b>Personal:</b>\nBeen allergic to grass.",
    "<b>Personal:</b>\nEaten the ends of a loaf of bread.",
    "<b>Personal:</b>\nBought a Car.",
    "<b>Personal:</b>\nGone on a Road Trip.",
    "<b>Personal:</b>\nBeen in a Natural Disaster.",
    "<b>Personal:</b>\nBeen to a Different Continent.",
    "<b>Personal:</b>\nDone Parkour.",
    "<b>Personal:</b>\nCrossdressed.",
    "<b>Personal:</b>\nHad a hangover.",
    "<b>Personal:</b>\nBaked a sweet.",
    "<b>Personal:</b>\nAccidentally confessed feelings for someone.",
    "<b>Personal:</b>\nBeen ignored.",
    "<b>Personal:</b>\nIgnored someone.",
    "<b>Personal:</b>\nBroken pc parts.",
    "<b>Personal:</b>\nPurposely did something above your own skill level for fun.",
    "<b>Personal:</b>\nDanced like no one was watching.",
    "<b>Personal:</b>\nProcrastinate.",
    "<b>Personal:</b>\nForgot to mute your mic and did something embarrassing.",
    "<b>Personal:</b>\nSaid something a little to loud in public.",
    "<b>Personal:</b>\nHad a rave in your car at a stoplight.",
    "<b>Personal:</b>\nHad a mental break down for no reason.",
    "<b>Personal:</b>\nPaid my own bills.",
    "<b>Personal:</b>\nBeen locked out.",
    "<b>Personal:</b>\nLocked yourself out.",
    "<b>Personal:</b>\nBeen threatened with a good time, then been severely disappointed.",
    "<b>Personal:</b>\nMade something for someone you care about.",
    "<b>Personal:</b>\nGet confused by your own parents.",
    "<b>Personal:</b>\nTook a friend out when they were having a bad day.",
    "<b>Personal:</b>\nAlmost been thrown out of your home.",
    "<b>Personal:</b>\nAccidentally ran over an animal while driving.",
    "<b>Personal:</b>\nWalked into a tree/pole while on your phone.",
    "<b>Personal:</b>\nCared about rights.",
    "<b>Personal:</b>\nGone to court.",
    "<b>Personal:</b>\nCried over spilled milk.",
    "<b>Personal:</b>\nPurposefully thrown a dodgeball at someone's head.",
    "<b>Personal:</b>\nGotten folded.",
    "<b>Personal:</b>\nDropped something on purpose, just to move closer to someone.",
    "<b>Personal:</b>\nSpilled my drink in a way that damaged something.",
    "<b>Personal:</b>\nGave someone answers to a test/homework.",
    "<b>Personal:</b>\nDonated Clothes to charity.",
    "<b>Personal:</b>\nBeen an extrovert.",
    "<b>Personal:</b>\nBought a last minute gift for someone important.",
    "<b>Personal:</b>\nTried to pay an artist in exposure.",
    "<b>Personal:</b>\nUsed a friends image to make a funny photoshop edit.",
    "<b>Personal:</b>\nAccidentally flashed someone.",
    "<b>Personal:</b>\nVisited an escape room.",
    "<b>Personal:</b>\nBite your tongue to save someone's feelings.",
    "<b>Personal:</b>\nPretended to like someone so u wouldn't hurt their feelings.",
    "<b>Personal:</b>\nFailed NNN in the first hour.",
    "<b>Personal:</b>\nMade it through NNN.",
    "<b>Personal:</b>\nCurrently believe in sex after marriage.",
    "<b>Personal:</b>\nBailed on someone.",
    "<b>Personal:</b>\nHad my birthday land on a holiday.",
    "<b>Personal:</b>\nWasted someone’s time on purpose.",
    "<b>Personal:</b>\nGone skydiving.",
    "<b>Personal:</b>\nPut metal in the microwave.",
    "<b>Personal:</b>\nKept a pet goldfish alive for two years or longer.",
    "<b>Personal:</b>\nGot an MRI scan.",
    "<b>Personal:</b>\nBought flowers for someone.",
    "<b>Personal:</b>\nTried chocolate covered crickets.",
    "<b>Personal:</b>\nMade a homemade Pizza.",
    "<b>Personal:</b>\nBeen caught staring at someone.",
    "<b>Personal:</b>\nTaken a longer than 30 min shower.",
    "<b>Personal:</b>\nRidden on a motorcycle.",
    "<b>Personal:</b>\nWoke up from a nap and was confused as to where i was.",
    "<b>Personal:</b>\nBeen really mad someone woke me up from a nap.",
    "<b>Personal:</b>\nWent into fantasyland in my head.",
    "<b>Personal:</b>\nBeen tired of metaverse/nft talk.",
    "<b>Personal:</b>\nGave up on friends and or family in order to make myself better.",
    "<b>Personal:</b>\nBeen tased or pepper sprayed.",
    "<b>Personal:</b>\nGot peed or pooped on by an animal.",
    "<b>Personal:</b>\nCried over a comic/manga/book.",
    "<b>Personal:</b>\nUnironically enjoyed roblox!",
    "<b>Personal:</b>\nGot Icy Hot where it did not belong.",
    "<b>Personal:</b>\nSent a message talking crap about someone to the person it was aimed at.",
    "<b>Personal:</b>\nSetup a false webcam to do other stuff for an online meeting of any kind.",
    "<b>Personal:</b>\nBeen in a airplane.",
    "<b>Personal:</b>\nStarted a new hobby.",
    "<b>Personal:</b>\nWanted to start a new hobby.",
    "<b>Personal:</b>\nCompared myself to others.",
    "<b>Personal:</b>\nGiven up on a dream because you think you aren't cut out for it.",
    "<b>Personal:</b>\nLived in the extreme cold.",
    "<b>Personal:</b>\nLived in the extreme heat.",
    "<b>Personal:</b>\nBeen to a resort.",
    "<b>Personal:</b>\nOwned a luxury car.",
    "<b>Personal:</b>\nExperienced hail! (raining ice).",
    "<b>Personal:</b>\nWalked an hour to school.",
    "<b>Personal:</b>\nHad your parent come in and hear you say a cuss word or something inappropriate.",
    "<b>Personal:</b>\nEaten glass!.",
    "<b>Personal:</b>\nDrank an energy drink, only to have it increase your heart beat.",
    "<b>Personal:</b>\nDrank from a natural water source.",
    "<b>Personal:</b>\nPunched something in your sleep.",
    "<b>Personal:</b>\nBroken a window.",
    "<b>Personal:</b>\nBroken a table.",
    "<b>Personal:</b>\nDone arts and crafts!.",
    "<b>Personal:</b>\nCreated my own gift for someone.",
    "<b>Personal:</b>\nGone Hiking.",
    "<b>Gaming:</b>\nSpent more than 1,000 dollars in a video game in 1 year.",
    "<b>Gaming:</b>\nBacked a game for more than 2,000 dollars.",
    "<b>Gaming:</b>\nHacked or modded in a game be it save game editing, aimbotting, currency manipulation, etc.",
    "<b>Gaming:</b>\nP*ssed in a bottle to avoid leaving a game.",
    "<b>Gaming:</b>\nPlayed a single game for more than 48 hours straight.",
    "<b>Gaming:</b>\nRoleplayed in an MMORPG.",
    "<b>Gaming:</b>\nBeen so toxic I made someone rage quit.",
    "<b>Gaming:</b>\nRage quit a game.",
    "<b>Gaming:</b>\nCared about game visual fidelity over game quality.",
    "<b>Gaming:</b>\nGot an ace clutch.",
    "<b>Gaming:</b>\nHurt someone while playing a game accidentally.",
    "<b>Gaming:</b>\nLost or removed someone as a friend due to a game.",
    "<b>Gaming:</b>\nBeen a pro player or in a games highest ranks.",
    "<b>Gaming:</b>\nGot an ace.",
    "<b>Gaming:</b>\nTook a game way too seriously.",
    "<b>Gaming:</b>\nEnjoyed playing casually.",
    "<b>Gaming:</b>\nWanted full body tracking.",
    "<b>Gaming:</b>\nPlayed VR.",
    "<b>Gaming:</b>\nExploited a game breaking bug, feature, or exploit to my own advantage.",
    "<b>Gaming:</b>\nBought and or sold an account.",
    "<b>Gaming:</b>\nWon any money or a trophy or title in a video game.",
    "<b>Gaming:</b>\nMade a friend, known them for over a year only to see them never login again.",
    "<b>Gaming:</b>\nSkipped school to play a game.",
    "<b>Gaming:</b>\nBeen a coach or mentor in a game.",
    "<b>Gaming:</b>\nPlayed against or with a hacker.",
    "<b>Gaming:</b>\nActually used pay to win options.",
    "<b>Gaming:</b>\nBought and or sold an in game currency.",
    "<b>Gaming:</b>\nBeen so mad at a game that I broke something.",
    "<b>Gaming:</b>\nConsidered or tried to become a streamer or youtube creator.",
    "<b>Gaming:</b>\nStreamed to literally no one for longer than an hour.",
    "<b>Gaming:</b>\nStreamed for 24 hours straight.",
    "<b>Gaming:</b>\nPlayed a game that deeply scared me.",
    "<b>Gaming:</b>\nPlayed games as a coping method.",
    "<b>Gaming:</b>\nSaved a game and committed atrocities.",
    "<b>Gaming:</b>\nFelt extremely let down by a game I badly wanted.",
    "<b>Gaming:</b>\nPre-ordered a game.",
    "<b>Gaming:</b>\nBought a Collector’s Edition of a game.",
    "<b>Gaming:</b>\nDonated more than 100 dollars to a streamer.",
    "<b>Gaming:</b>\nWatched a streamer who had no viewers.",
    "<b>Gaming:</b>\nPlayed a game since Alpha.",
    "<b>Gaming:</b>\nCreated mods for a game.",
    "<b>Gaming:</b>\nWorked in game development in any form.",
    "<b>Gaming:</b>\nBuilt a PC.",
    "<b>Gaming:</b>\nMade a real girlfriend or boyfriend in a game.",
    "<b>Gaming:</b>\nHosted a rented server.",
    "<b>Gaming:</b>\nPassed out while gaming.",
    "<b>Gaming:</b>\nUsed 2 or more monitors.",
    "<b>Gaming:</b>\nBeen to a gaming related convention.",
    "<b>Gaming:</b>\nBelieved I play games better when intoxicated.",
    "<b>Gaming:</b>\nBought hacks and or mods for a game.",
    "<b>Gaming:</b>\nPushed a friend off a cliff.",
    "<b>Gaming:</b>\nLegitimately beat minecraft.",
    "<b>Gaming:</b>\nKilled myself checking for fall damage.",
    "<b>Gaming:</b>\nLost so much progress in a game I quit.",
    "<b>Gaming:</b>\nFallen into lava.",
    "<b>Gaming:</b>\nCried over a video game.",
    "<b>Gaming:</b>\nBuilt my own PC.",
    "<b>Gaming:</b>\nBought a pre-built PC.",
    "<b>Gaming:</b>\nYelled at someone because of a video game.",
    "<b>Gaming:</b>\nPlayed Minecraft.",
    "<b>Gaming:</b>\nGot a game because of friends/a friend.",
    "<b>Gaming:</b>\nPlayed a rhythm game.",
    "<b>Gaming:</b>\nPlayed a retro arcade game.",
    "<b>Gaming:</b>\nGotten a large kill streak in an FPS.",
    "<b>Gaming:</b>\nPlayed a game with an age rating higher than your own age.",
    "<b>Gaming:</b>\nWanted a game so bad I begged a friend to buy it for me. patreon.",
    "<b>Gaming:</b>\nMade money from selling a service in a game.",
    "<b>Gaming:</b>\nBeen so invested in a game I could tell you the lore to literally everything.",
    "<b>Gaming:</b>\nCosplayed as a video game character.",
    "<b>Gaming:</b>\nBeen griefed to the point I gave up on the server and/or game.",
    "<b>Gaming:</b>\nEnjoyed Indie games more than triple A titles.",
    "<b>Gaming:</b>\nGotten all achievements in a game.",
    "<b>Gaming:</b>\nPlayed D&D.",
    "<b>Gaming:</b>\nOwned over 200 games on Steam.",
    "<b>Gaming:</b>\nHad more than 1000 hours on a single game.",
    "<b>Gaming:</b>\nKilled my Tamagotchi.",
    "<b>Gaming:</b>\nBeaten a chess bot.",
    "<b>Gaming:</b>\nPlayed nintendo wii.",
    "<b>Gaming:</b>\nPlayed xbox 360.",
    "<b>Gaming:</b>\nPlayed ps3.",
    "<b>Gaming:</b>\nWent back to a game I played a ton as a kid only to realize it kinda sucked.",
    "<b>Gaming:</b>\nBeen addicted to a game.",
    "<b>Gaming:</b>\nHave 10,000 or more hours in a game.",
    "<b>Gaming:</b>\nBought a game for a friend only to watch as they never played it.",
    "<b>Gaming:</b>\nGotten bored of a game.",
    "<b>Gaming:</b>\nCried at the loss of an animal in a video game.",
    "<b>Gaming:</b>\nBeaten a videogame with a group of friends.",
    "<b>Gaming:</b>\nPrefer single player video games over multiplayer.",
    "<b>Gaming:</b>\nPrefer multiplayer video games over single player.",
    "<b>Gaming:</b>\nHad my video games taken away as punishment from my parents.",
    "<b>Gaming:</b>\nOwned a computer worth more than $1,000.",
    "<b>Gaming:</b>\nPlayed a gacha game.",
    "<b>Gaming:</b>\nPlayed an Electronic Arts game (i.e. Battlefield, Apex, or Battlefront).",
    "<b>Gaming:</b>\nPlayed a MOBA (i.e. DOTA or League of Legends).",
    "<b>Gaming:</b>\nCompleted a game on its hardest difficulty.",
    "<b>Gaming:</b>\nBroken a controller while rage quitting.",
    "<b>Gaming:</b>\nPlaced my minecraft bed next to someone else's uwu.",
    "<b>Gaming:</b>\nHunted Easter eggs/secrets.",
    "<b>Gaming:</b>\nHad everything blamed on you because you were a support class.",
    "<b>Gaming:</b>\nBlamed everything on your support.",
    "<b>Gaming:</b>\nGot 100% completion on an open world game.",
    "<b>Gaming:</b>\nSpeed ran a game.",
    "<b>Gaming:</b>\nWon in a ranked chess game.",
    "<b>Gaming:</b>\nPlayed chess.",
    "<b>Gaming:</b>\nPlayed Checkers.",
    "<b>Gaming:</b>\nBeen subscribed to a game for more than a year.",
    "<b>Music:</b>\nSang in a choir.",
    "<b>Music:</b>\nPlayed or sang on stage.",
    "<b>Music:</b>\nLoved all forms of music and meant it.",
    "<b>Music:</b>\nBeen to a music festival.",
    "<b>Music:</b>\nBeen to a rave.",
    "<b>Music:</b>\nUsed my musical talent in a professional setting.",
    "<b>Music:</b>\nBeen recruited for a band or orchestra.",
    "<b>Music:</b>\nTaught someone how to play an instrument.",
    "<b>Music:</b>\nPlayed an electric instrument.",
    "<b>Music:</b>\nPlayed an acoustic instrument.",
    "<b>Music:</b>\nSang karaoke.",
    "<b>Music:</b>\nHad a song for every emotion or feeling.",
    "<b>Music:</b>\nFelt deeply touched by music.",
    "<b>Music:</b>\nMade a playlist that has over 200 songs in it.",
    "<b>Music:</b>\nBeen complimented about my musical taste.",
    "<b>Music:</b>\nBeen a real groupie.",
    "<b>Music:</b>\nOwned a VIP or backstage access pass to a concert.",
    "<b>Music:</b>\nSpent more than 500 dollars at a concert.",
    "<b>Music:</b>\nBeen in a mosh pit.",
    "<b>Music:</b>\nTaught myself an instrument.",
    "<b>Music:</b>\nBeen able to read sheet music.",
    "<b>Music:</b>\nEnjoyed a remix more than original.",
    "<b>Music:</b>\nBeen a lead singer.",
    "<b>Music:</b>\nBelieved music can save lives.",
    "<b>Music:</b>\nEnjoyed an anime's music.",
    "<b>Music:</b>\nListened to a song I loved so many times I hated it.",
    "<b>Music:</b>\nHad a bad day fixed by a song.",
    "<b>Music:</b>\nAbsolutely lost my gourd when someone played my favorite song.",
    "<b>Music:</b>\nStarted a song over cause I realized I wasn't listening to it and I wanted to.",
    "<b>Music:</b>\nTried to share obscure music with others.",
    "<b>Music:</b>\nCame up with choreography to a song that had none.",
    "<b>Music:</b>\nMade up lyrics.",
    "<b>Music:</b>\nRecognized a song's genre by listening to it.",
    "<b>Music:</b>\nBeat-boxed.",
    "<b>Music:</b>\nStarted out hating a song only to later fall in love with it.",
    "<b>Music:</b>\nOnly used free streaming services.",
    "<b>Music:</b>\nListen to a 10 hour version of a song.",
    "<b>Music:</b>\nEnjoyed Classical Music and meant it.",
    "<b>Music:</b>\nBeen to concert outside my state/country.",
    "<b>Music:</b>\nListened to music to fall asleep.",
    "<b>Music:</b>\nSang the song that never ends.",
    "<b>Music:</b>\nWrote my own song.",
    "<b>Music:</b>\nDownloaded music off the internet and got a virus.",
    "<b>Music:</b>\nBeen a conductor.",
    "<b>Music:</b>\nBurned a CD for my car.",
    "<b>Music:</b>\nUsed music to calm me down.",
    "<b>Music:</b>\nCreated my own beat.",
    "<b>Music:</b>\nSeen a video game orchestra.",
    "<b>Music:</b>\nMade a friend at a concert.",
    "<b>Music:</b>\nBought merch at a concert.",
    "<b>Music:</b>\nBeen able to play at least 3 different instruments.",
    "<b>Music:</b>\nOwned more than 5 instruments.",
    "<b>Music:</b>\nPlayed Brass (i.e. Trumpet and Trombone).",
    "<b>Music:</b>\nPlayed Woodwinds (i.e. Flute and Clarinet).",
    "<b>Music:</b>\nPlayed Percussion (i.e. Drums and Piano).",
    "<b>Music:</b>\nOwned a vinyl record.",
    "<b>Music:</b>\nGotten goosebumps from listening to a song.",
    "<b>Music:</b>\nComposed music using a computer program.",
    "<b>Music:</b>\nPlayed improv music.",
    "<b>Music:</b>\nRecorded in a music studio.",
    "<b>Music:</b>\nBeen an audiophile.",
    "<b>Music:</b>\nTraveled more than 1,000 Miles (1,609 Kilometers) on tour.",
    "<b>Music:</b>\nPlayed Strings (i.e. Violin and Classical Guitar).",
    "<b>Music:</b>\nOwned over $5,000 in musical instruments/equipment.",
    "<b>Music:</b>\nLearned a song from a game on an instrument.",
    "<b>Music:</b>\nRecognized a song just by hearing a few seconds of it.",
    "<b>VRChat:</b>\nERPD.",
    "<b>VRChat:</b>\nSang on stage in a public lobby.",
    "<b>VRChat:</b>\nBeen promoted to known or trusted user.",
    "<b>VRChat:</b>\nBeen demoted from known or trusted user.",
    "<b>VRChat:</b>\nGave someone a virtual hug.",
    "<b>VRChat:</b>\nGave someone headpats.",
    "<b>VRChat:</b>\nGave someone a virtual smooch.",
    "<b>VRChat:</b>\nFell for someone without knowing what they looked like.",
    "<b>VRChat:</b>\nBeen overly curious about someone in a lobby.",
    "<b>VRChat:</b>\nBeen a nuisance.",
    "<b>VRChat:</b>\nBeen blocked not by friends.",
    "<b>VRChat:</b>\nBeen muted.",
    "<b>VRChat:</b>\nHad my avatar hidden.",
    "<b>VRChat:</b>\nCrashed someone.",
    "<b>VRChat:</b>\nBeen toxic.",
    "<b>VRChat:</b>\nRemembered the old VRChat days.",
    "<b>VRChat:</b>\nBeen apart of a VRChat gang.",
    "<b>VRChat:</b>\nRemoved a toxic friend.",
    "<b>VRChat:</b>\nBeen a jerk to a new user.",
    "<b>VRChat:</b>\nStared at a mirror for more than 2 hours.",
    "<b>VRChat:</b>\nHad virtual cuddles.",
    "<b>VRChat:</b>\nStayed up really late talking about life.",
    "<b>VRChat:</b>\nBeen to a VRChat \"Event\" ;)",
    "<b>VRChat:</b>\nConsidered myself a dancer.",
    "<b>VRChat:</b>\nCould approach someone to flirt with in a public lobby.",
    "<b>VRChat:</b>\nUploaded an avatar.",
    "<b>VRChat:</b>\nUploaded a world.",
    "<b>VRChat:</b>\nUsed a crasher.",
    "<b>VRChat:</b>\nUsed Ugandan knuckles.",
    "<b>VRChat:</b>\nDrawn something cool.",
    "<b>VRChat:</b>\nPurchased an avatar.",
    "<b>VRChat:</b>\nCrashed.",
    "<b>VRChat:</b>\nFell asleep in a public lobby.",
    "<b>VRChat:</b>\nBeen simped on.",
    "<b>VRChat:</b>\nUsed a voice changer.",
    "<b>VRChat:</b>\nBeen apart of a group that uses the same avatar and acted goofy.",
    "<b>VRChat:</b>\nBottle flipped.",
    "<b>VRChat:</b>\nEnjoyed music played over someones mic.",
    "<b>VRChat:</b>\nWon in among us VRChat.",
    "<b>VRChat:</b>\nWon Uno in VRChat.",
    "<b>VRChat:</b>\nWon in Murder.",
    "<b>VRChat:</b>\nWon The Devouring map.",
    "<b>VRChat:</b>\nHosted Never Have I Ever.",
    "<b>VRChat:</b>\nWatched a movie in VRChat.",
    "<b>VRChat:</b>\nBeen to the Void Club and actually danced.",
    "<b>VRChat:</b>\nPurposefully slept in VRChat.",
    "<b>VRChat:</b>\nGotten blackout drunk in VRChat.",
    "<b>VRChat:</b>\nLearned enough sign language to communicate with mutes.",
    "<b>VRChat:</b>\nWon a round of freeze tag in VRChat.",
    "<b>VRChat:</b>\nBeen a mute.",
    "<b>VRChat:</b>\nPlayed on desktop.",
    "<b>VRChat:</b>\nUsed avatars of characters from well-known franchises.",
    "<b>VRChat:</b>\nTried to get into VRChat.",
    "<b>VRChat:</b>\nBroke my VR setup.",
    "<b>VRChat:</b>\nDamaged any part of my VR equipment.",
    "<b>VRChat:</b>\nInstalled VRChat mods.",
    "<b>VRChat:</b>\nCurrently using VRChat mods.",
    "<b>VRChat:</b>\nHit something IRL while dancing in VR.",
    "<b>VRChat:</b>\nHave phantom sense.",
    "<b>VRChat:</b>\nForgot I was in VR.",
    "<b>VRChat:</b>\nGot too invested into VRChat.",
    "<b>VRChat:</b>\nBeen sad looking at my friends list.",
    "<b>VRChat:</b>\nGave someone you just met in a lobby advice.",
    "<b>VRChat:</b>\nInstantly knew a person you met would be your best VR friend.",
    "<b>VRChat:</b>\nGotten a friend into VRChat!",
    "<b>VRChat:</b>\nLost a friend group due to drama.",
    "<b>VRChat:</b>\nDid a handstand in VR.",
    "<b>VRChat:</b>\nLeft a lobby as soon as I heard them youngins.",
    "<b>VRChat:</b>\nHeard some pretty messed up stuff in a public lobby.",
    "<b>VRChat:</b>\nHad to protect a friend in a public lobby.",
    "<b>VRChat:</b>\nFallen asleep in a public lobby.",
    "<b>VRChat:</b>\nJumped into a portal without checking where it lead.",
    "<b>VRChat:</b>\nJoined a friend by mistake and felt like i had to stay.",
    "<b>VRChat:</b>\nTrapped Somebody.",
    "<b>VRChat:</b>\nMet a famous VRchat Streamer or Youtuber. Ex Lolathon.",
    "<b>VRChat:</b>\nInstantly fallen for someone in a lobby.",
    "<b>VRChat:</b>\nGhosted a friend group.",
    "<b>VRChat:</b>\nSeen people erp in a public lobby.",
    "<b>VRChat:</b>\nHad to explain a conversation I had in vrchat to my parent.",
    "<b>VRChat:</b>\nPut my parent in vrchat.",
    "<b>VRChat:</b>\nWatched an anime in VRChat.",
    "<b>VRChat:</b>\nPlayed until your fbt trackers died.",
    "<b>VRChat:</b>\nTrolled the AFK player.",
    "<b>VRChat:</b>\nTaken part in a raid.",
    "<b>VRChat:</b>\nPlayed on vrchat on Christmas Day.",
    "<b>VRChat:</b>\nVisited a VRChat rave.",
    "<b>VRChat:</b>\nHad someone recognize the game/movie/TV Show your avatar is from.",
    "<b>VRChat:</b>\nUploaded more than 100 avatars.",
    "<b>VRChat:</b>\nDone Karaoke in VR.",
    "<b>VRChat:</b>\nPre-ordered VR equipment.",
    "<b>VRChat:</b>\nTricked/made someone go into a Ugandan Knuckles portal.",
    "<b>VRChat:</b>\nOwned more than one VR headset.",
  };
  
  public void Start() {
    Debug.Log(questions.Length + " Total Questions loaded (NHIE)");
    masterToggle.isOn = masterLocked;
    if (Networking.LocalPlayer.isMaster) {
      currentUsername = Networking.LocalPlayer.displayName;
      usernameText.text = currentUsername;
      RequestSerialization();
    }
  }
  public override void OnDeserialization() {
    if (previousText != currentText) {
      Debug.Log("NHIE updated: " + currentText + " " + (currentText < 0 ? "" : questions[currentText]));
    }
    if (masterToggle.isOn != masterLocked) {
      Debug.Log("NHIE Master Lock: " + masterLocked + " (am master: " + Networking.LocalPlayer.isMaster + ")");
    }
    previousText = currentText;
    if (currentText >= 0) {
      textBox.text = questions[currentText];
    } else if (currentText == -1) {
      textBox.text = "Played \"Never Have I Ever\"";
    } else {
      textBox.text = "";
    }
    masterToggle.isOn = masterLocked;
    usernameText.text = currentUsername;
  }
  public void ClickedRandom() {
    if (masterLocked && !Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    previousText = currentText = Random.Range(0, questions.Length);
    if (currentText >= 0) {
      textBox.text = questions[currentText];
    } else if (currentText == -1) {
      textBox.text = "Played \"Never Have I Ever\"";
    } else {
      textBox.text = "";
    }
    RequestSerialization();
  }
  public void ClickedClear() {
    if (masterLocked && !Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    textBox.text = "";
    previousText = currentText = -2;
    RequestSerialization();
  }
  public void ToggleMasterLock() {
    Debug.Log("Toggling Master Lock: I am Master (" + Networking.LocalPlayer.isMaster + "), currently (" + masterLocked + ")");
    if (!Networking.LocalPlayer.isMaster) return;
    if (!Networking.IsOwner(gameObject)) {
      Networking.SetOwner(Networking.LocalPlayer, gameObject);
    }
    masterLocked = !masterLocked;
    // masterToggle.isOn = masterLocked;
    Debug.Log("Toggling Master Lock Updated to (" + masterLocked + ")");

    RequestSerialization();
    if (clickSound != null) clickSound.PlayOneShot(clickSound.clip, 1.0f);
  }
}
